<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
     
		<div class="custom-form-wrapper addnew">
        
        <div class="col-md-10 col-md-offset-1">
        	<!--<div class="row">
           <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
           </div>
-->
        	<h1><?php echo $this->pageHeadingshow ?></h1>
            <hr />
            <div class="row">
            <div class="row">
                		<b>Note:</b> Please upload	either a .xls,.xlsx, or .csv (comma delimited) file spreadsheet
Columns :  Teacher First Name, Teacher Last Name, Classes (multiple group classes delimited with a semi-colon)



 <a href="<?php echo APPLICATION_URL ?>/download.php?download_file=public/resources/sample_files/teacher_classes.xls">Download Sample File</a>

                </div>
                <br />
            	<div class="row">
                		
               		<?php echo $this->form ?>
                </div>
                
                <br />
                <br />
                <div class="row">
                	<div class="portlet-body">
				
						<form action="<?php echo $this->baseUrl() ?>/admin/user/remove" method="post" onsubmit="return checkSelects();" >
			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
								<th>File Name</th>
                                <th>Error Log</th>
								<th>Added Date</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			
			</form>
			
			</div>
                </div>
            </div>
            
         </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
  		"bAutoWidth": false,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/bulkimport/getimportteacher/type/6" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		
		}
	} );
});

function removeclass(idval)
{
		var confirmval=confirm("Are you sure you want to remove this family");
		if(confirmval)
		{
			window.location.href="<?php echo SITE_HTTP_URL ?>/student/removestudent/idval/"+idval;
		}
}
</script>
