<?php 
	$user =  $this->user_information ;

	$modelSuper = new Application_Model_SuperModel();
?>
<!-- BEGIN PAGE CONTENT-->
<div class="row profile">
	<div class="col-md-12">
		<!--BEGIN TABS-->
		<div class="tabbable tabbable-custom tabbable-full-width">
			<ul class="nav nav-tabs">
				<li class="active">	<a href="#tab_1_1" data-toggle="tab"> Overview </a>	</li>
 			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab_1_1">
					<div class="row">
						<div class="col-md-3">
							<ul class="list-unstyled profile-nav">
								<li><img src="<?php echo getUserImage($user['user_image'],'thumb')?>" class="img-responsive" alt=""/></li>
								<li><a href="<?php echo $this->baseUrl("admin/user/account/user_id/".$user['user_id'])?>">Update Profile </a></li>
								<li><a href="<?php echo $this->baseUrl("admin/user/password/user_id/".$user['user_id'])?>">Update Password </a></li>
								<li><a href="<?php echo $this->baseUrl("admin/user/image/user_id/".$user['user_id'])?>">Update Image </a></li>
								 
							</ul>
						</div>
						
					 
						<div class="col-md-9">
							<div class="row">
								<div class="col-md-8 profile-info">
									<h1><?php echo ucwords($user['user_first_name']." ".$user['user_last_name'])." <br />";
									//pr($user);
									if(!empty($user['user_email']))
									{
									echo "<small>(".$user['user_email'].") </small>";
									
									}
									?></h1>
									<ul class="list-inline">
										<?php if($user['user_country']!=''){?><li><i class="fa fa-map-marker"></i> <?php echo ucwords($user['user_country']);?></li><?php }?>
										<?php if($user['user_created']!=''){?><li><i class="fa fa-calendar"></i> <?php echo date('d M Y',strtotime($user['user_created'])); ?></li><?php }?>
 									</ul>
									
									<div class="custom-form-wrapper">
                                    
										<?php echo $this->form;?>
									</div>
 								</div>
								
							
							</div>
							<!--end row-->
						</div>
					</div>
				</div>
				<!--tab_1_2-->
			</div>
		</div>
		<!--END TABS-->
	</div>
</div>
<!-- END PAGE CONTENT-->

