<?php 
	$user =  $this->user_information ;
?>
<!-- BEGIN PAGE CONTENT-->
<div class="row profile">
	<div class="col-md-12">
		<!--BEGIN TABS-->
		<div class="tabbable tabbable-custom tabbable-full-width">
			<ul class="nav nav-tabs">
				<li class="active">	<a href="#tab_1_1" data-toggle="tab"> Payment Report </a>	</li>
 			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab_1_1">
                    <div class="row">
								<div class="col-md-8 profile-info">
									<h1><?php echo $this->user_information['user_first_name']." ".$this->user_information['user_last_name'] ; ?> <br><small>(<?php echo $this->user_information['user_email']  ?>) </small></h1>
									
									
									<div class="custom-form-wrapper">
                                    <?php
									if(isset($this->subscription_detail['subscription_plantitle']) && !empty($this->subscription_detail['subscription_plantitle']))
									{
									?>
                                    <div class="row">
                                            <div class="col-md-5">Plan  Name:</div>
                                            <div class="col-md-7"><?=$this->subscription_detail['subscription_plantitle']?></div>
                                    </div>
                                    <br />
                                    <?php	
									}
									 ?>
                                     <?php
									if(isset($this->subscription_detail['subscription_plandes']) && !empty($this->subscription_detail['subscription_plandes']))
									{
									?>
                                    <div class="row">
                                            <div class="col-md-5">Plan Description:</div>
                                            <div class="col-md-7"><?=$this->subscription_detail['subscription_plandes']?></div>
                                    </div>
                                    <br />
                                    <?php	
									}
									 ?>
                                       <?php
									if(isset($this->subscription_detail['subscription_planprice']) && !empty($this->subscription_detail['subscription_planprice']))
									{
									?>
                                    <div class="row">
                                            <div class="col-md-5">Plan Amount:</div>
                                            <div class="col-md-7"><?php echo $this->site_configs['site_currency'].$this->subscription_detail['subscription_planprice']." Per month"?></div>
                                    </div>
                                    <br />
                                    <?php	
									}
									 ?>
                                     
                                     <?php
									if(isset($this->subscription_detail['subscription_planprice']) && !empty($this->subscription_detail['subscription_planprice']))
									{
									?>
                                    <div class="row">
                                            <div class="col-md-5">Subscription Start Date:</div>
                                            <div class="col-md-7"><?php echo date('M-d-Y h:i A', strtotime($this->subscription_detail['subscription_start_date']))  ?></div>
                                    </div>
                                    <br />
                                    <?php	
									}
									 ?>
                                     
                                       <?php
									if(isset($this->subscription_detail['subscription_userfirstname']) && !empty($this->subscription_detail['subscription_userfirstname']))
									{
									?>
                                    <div class="row">
                                            <div class="col-md-5">User Name:</div>
                                            <div class="col-md-7"><?php echo $this->subscription_detail['subscription_userfirstname']." ".$this->subscription_detail['subscription_userlastname'] ?></div>
                                    </div>
                                    <br />
                                    <?php	
									}
									 ?>
                                    		
										</div>
 								</div>
								
								<!--end col-md-8-->
								
								<!--end col-md-4-->
							</div>
				</div>
				<!--tab_1_2-->
			</div>
		</div>
		<!--END TABS-->
	</div>
</div>
<!-- END PAGE CONTENT-->

