<?php $user = new Application_Model_User();?>
		
		
		
		<!-- BEGIN DASHBOARD STATS -->
		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<div class="dashboard-stat blue-madison">
					<div class="visual">
						<i class="fa fa-users"></i>
					</div>
					<div class="details">
						<div class="number">
							<?php echo $user->getCount();?>
						</div>
						<div class="desc">
							All Users
						</div>
					</div>
					<a class="more"  href="<?php echo $this->baseUrl()?>/admin/user">
					View more <i class="m-icon-swapright m-icon-white"></i>
					</a>
				</div>
			</div>
			
			
			 
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<div class="dashboard-stat green-haze">
					<div class="visual">
						<i class="fa fa-users"></i>
					</div>
					<div class="details">
						<div class="number">
							 <?php echo $this->countschool ?>
						</div>
						<div class="desc">
							Schools
						</div>
					</div>
					<a class="more"  href="<?php echo $this->baseUrl()?>/admin/user/schooluser">
					View more <i class="m-icon-swapright m-icon-white"></i>
					</a>
				</div>
			</div>
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<div class="dashboard-stat purple-plum">
					<div class="visual">
						<i class="fa fa-users"></i>
					</div>
					<div class="details">
						<div class="number">
							 <?php echo $this->countstudent ?>
						</div>
						<div class="desc">
							 Students
						</div>
					</div>
						<a class="more"  href="<?php echo $this->baseUrl()?>/admin/user/studentuser">
					View more <i class="m-icon-swapright m-icon-white"></i>
					</a>
				</div>
			</div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<div class="dashboard-stat blue">
					<div class="visual">
						<i class="fa fa-users"></i>
					</div>
					<div class="details">
						<div class="number">
							 <?php echo $this->countteacher ?>
						</div>
						<div class="desc">
							Teachers
						</div>
					</div>
					<a class="more"  href="<?php echo $this->baseUrl()?>/admin/user/teacheruser">
					View more <i class="m-icon-swapright m-icon-white"></i>
					</a>
				</div>
			</div>
		</div>
		<!-- END DASHBOARD STATS -->
		
		
		<div class="clearfix"></div>
		
	 
		<div class="row ">
			
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<div class="dashboard-stat yellow">
					<div class="visual">
						<i class="fa fa-users"></i>
					</div>
					<div class="details">
						<div class="number">
							 <?php echo $this->countsubadmins ?>
						</div>
						<div class="desc">
							School Sub Admins
						</div>
					</div>
						<a class="more"  href="<?php echo $this->baseUrl()?>/admin/user/schoolsubadminuser">
					View more <i class="m-icon-swapright m-icon-white"></i>
					</a>
				</div>
			</div>
            
            
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<div class="dashboard-stat red">
					<div class="visual">
						<i class="fa fa-users"></i>
					</div>
					<div class="details">
						<div class="number">
							 <?php echo $this->countfamilies ?>
						</div>
						<div class="desc">
							Families
						</div>
					</div>
						<a class="more"  href="<?php echo $this->baseUrl()?>/admin/user/familyuser">
					View more <i class="m-icon-swapright m-icon-white"></i>
					</a>
				</div>
			</div>
            
			
		</div>


 
