<div class="row">
	<div class="slider_bottom">
    	<div class="container">
        		<div class="first_text">
                <?php echo $this->site_configs['home_page_first'] ?>
                <!--Lorem Ipsum is simply dummy text of the <span>printing and typestteing</span> industry.-->
                </div>
                <div class="second_text">
                <?php echo $this->site_configs['home_page_second'] ?>
                <!--Lorem Ipsum has been the industry's-->
                </div>
        </div>
    </div>
    <div class="row" id="features">
    <div class="row">
    	<div class="container">
        	<div class="row reviewdiv">
        	<div class="col-md-6 text-left">
            	<img src="<?php echo HTTP_SITEIMG_PATH ?>/pc_image.png"	  />
            </div>
            <div class="col-md-6">
            	<div class="row review_text">
                	Review your lessons from home or mobile device
                </div>
                <div class="review_des">
                 <?php echo $this->site_configs['review_from_home'] ?>
                <!--Lorem Ipsum is simply dummy text of the   and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. when an unknown printer took.-->
                </div>
                <div class="row checkout">
                Check Out  <img src="<?php echo HTTP_SITEIMG_PATH ?>/arrow.png"  />
                </div>
            </div>
            </div>
        </div>
    </div>
    <div class="row">
    	<div class="container">
        	
        	<div class="row reviewdiv">
            <div class="col-md-6">
            	<div class="row review_text">
                	Connect different file types everywhere
                </div>
                <div class="review_des">
                <?php echo $this->site_configs['differ_file_type'] ?>
                
                <!--Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. when an unknown printer took a galley of type and scrambled it to make a type specimen book.-->
                
                </div>
                <div class="row checkout">
                Check Out  <img src="<?php echo HTTP_SITEIMG_PATH ?>/arrow.png"  />
                </div>
            </div>
        	<div class="col-md-6 text-right">
            	<img src="<?php echo HTTP_SITEIMG_PATH ?>/group_icon.png"	  />
            </div>
            
            </div>
        </div>
    </div>
    <div class="row gray_back">
    	<div class="container">
        	
        	<div class="row reviewdiv">
            <div class="col-md-6 text-left">
            	<img src="<?php echo HTTP_SITEIMG_PATH ?>/student.png"	  />
            </div>
            <div class="col-md-6">
            	<div class="row review_text">
                	For Student / Family
                </div>
                <div class="review_des">
                <?php echo $this->site_configs['for_student'] ?>
                <!--Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. when an unknown printer took a galley of type and scrambled it to make a type specimen book.--></div>
                <div class="row checkout">
                Check Out  <img src="<?php echo HTTP_SITEIMG_PATH ?>/arrow.png"  />
                </div>
            </div>
        	
            </div>
        </div>
    </div>
    <div class="row">
    	<div class="container">
        	
        	<div class="row reviewdiv">
            <div class="col-md-6">
            	<div class="row review_text">
                	For Teachers
                </div>
                <div class="review_des">
                <?php echo $this->site_configs['for_teachers'] ?>
                <!--Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. when an unknown printer took a galley of type and scrambled it to make a type specimen book.--></div>
                <div class="row checkout">
                Check Out  <img src="<?php echo HTTP_SITEIMG_PATH ?>/arrow.png"  />
                </div>
            </div>
        	<div class="col-md-6 text-right">
            	<img src="<?php echo HTTP_SITEIMG_PATH ?>/teacher.png"	  />
            </div>
            
            </div>
        </div>
    </div>
    <div class="row gray_back">
    	<div class="container">
        	<div class="row reviewdiv">
            <div class="col-md-6 text-left">
            	<img src="<?php echo HTTP_SITEIMG_PATH ?>/admin.png"	  />
            </div>
            <div class="col-md-6">
            	<div class="row review_text">
                	School Admin
                </div>
                <div class="review_des">
                <?php echo $this->site_configs['school_admin'] ?>
                <!--Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. when an unknown printer took a galley of type and scrambled it to make a type specimen book.--></div>
                <div class="row checkout">
                Check Out  <img src="<?php echo HTTP_SITEIMG_PATH ?>/arrow.png"  />
                </div>
            </div>
        	
            </div>
        </div>
    </div>
    
    
    
    <div class="row all_features">
    	<div class="container">
        	<div class="row text-center rewind_head">
            	Using Lesson Rewind is simple for everyone
            </div>
            <div class="row text-center">
            	<div class="block_div">
                	<img src="<?php echo HTTP_SITEIMG_PATH?>/assignment.png"  />
                    <br />
                    <span>Teacher creates an assignment </span>
                </div>
                <div class="arrow_div">
                	<img src="<?php echo HTTP_SITEIMG_PATH?>/big_arrow.png"  />
                </div>
                <div class="block_div">
                	<img src="<?php echo HTTP_SITEIMG_PATH?>/pin.png"  />
                    <br />
                    <span>Attach video, audio, images and links </span>
                </div>
                  <div class="arrow_div">
                	<img src="<?php echo HTTP_SITEIMG_PATH?>/big_arrow.png"  />
                </div>
                <div class="block_div">
                	<img src="<?php echo HTTP_SITEIMG_PATH?>/bell.png"  />
                    <br />
                    <span>Notification is sent direct to the family</span>
                </div>
                  <div class="arrow_div">
                	<img src="<?php echo HTTP_SITEIMG_PATH?>/big_arrow.png"  />
                </div>
                <div class="block_div">
                	<img src="<?php echo HTTP_SITEIMG_PATH?>/phone.png"  />
                    <br />
                    <span>Families can review their lessons anytime </span>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="row more_info">
    	<div class="container text-center more_button_parent">
        		<div class="more_button">For Information on Using Lesson Rewind at Your Studio</div>
        </div>
    </div>
    
</div>
<?php  

 if($this->param=='feature'){?>
<script>
		var catTopPosition = jQuery('#features').offset().top;
   	    jQuery('html, body').animate({scrollTop:catTopPosition}, 'slow');
</script>

<?php } ?>