<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<h4>OUR FIT PROMISE</h4>
		<p>If your order is anything less than what you expected, let us know and we will make it right.</p>
		
		<h4>FREE GLOBAL SHIPPING</h4>
		<p>On orders over $150.</p>
	
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6">
		<div class="form-signin">
			<h2 class="form-signin-heading"><?php echo $this->pageHeading;?></h2>
			<p> 
				<a id="facebook_icon"  href="<?php echo  $this->url(array(),'facebook_signup')?>"><img src="<?php echo HTTP_IMG_PATH?>/icon-facebook-signup.png" alt="" /></a>
				
				<a id="twitter_icon"  href="<?php echo  $this->url(array(),'twitter_signup')?>"><img src="<?php echo HTTP_IMG_PATH?>/icon-twitter-signup.png" alt="" /></a>
			</p>
			
			<form method="post">
				<input type="text"  name="test" />
			
			</form>
			
			
 
 			<p></p>
 			<p><a href="<?php echo $this->url(array(),'front_register')?>">Sign Up</a> | <a href="<?php echo $this->url(array(),'front_forgotpassword')?>">Forgot Password</a></p>
			
 		</div>
	</div>
</div>
