<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid page-404">
            <div class="span5 number">404</div>
            <div class="span7 details">
                <h3>Opps, You're lost.</h3>
                
                <h1><?php echo $this->message ?></h1>

				<?php echo @$this->hiddenmessage ?>
                <?php if (isset($this->exception)): ?>
                <p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
                <?php endif ?>
                
				<?php if(1){?>
                <!--Erorr Phtml  -->
                <!-- pages       -->
                <h1><?php echo $this->message ?></h1>
                <?php echo @$this->hiddenmessage ?>
                <?php if (isset($this->exception)): ?>
                
                <h3>Exception information:</h3>
                <p>
                <b>Message:</b> <?php echo $this->exception->getMessage() ?>
                </p>
                
                <?php if(isset($this->lastQuery)){ ?>
                <p>
                <b>Last Query:</b> <pre><?php print_r($this->lastQuery); ?></pre>
                </p>
                <?php } ?>
                
                
                <h3>Stack trace:</h3>
                <pre><?php echo $this->exception->getTraceAsString(); ?>
                </pre>
                
                <h3>Request Parameters:</h3>
                <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
                </pre>
                
                <?php endif ?>
                
                <?php } ?>
                


            </div>
        </div>
    </div>
</div>