<style>
.main-container-outer
{
	width:100% !important;
	padding:0px !important;
	max-width: 100% !important;
}
</style>
<div class="row">
<div class="row banner">
 <?php 
	
	
		?>
        <img src="<?php echo HTTP_SITEIMG_PATH?>/bw-banner-contact.jpg"  />
        <?php	

	
	?>

</div>
<br />
<br />
<div class="container">
	<div class="row">
	<div class="col-lg-8 col-md-8 col-sm-8">
		<h2 class="form-signin-heading"><?php echo $this->pageHeading;?></h2>
		<?php echo $this->form;?>
        <br />
	</div>
	
	<div class="col-lg-4 col-md-4 col-sm-4">
		 <p></p>
		<?php echo $this->content['page_content']?>
	</div>
	</div>
</div></div>