<div class="row-fluid">
	<div class="span8 our-team-left ">
    	<?php echo $this->getHelper('Messages')->getMessages();?>
        <h1 class="team-heading"><?php echo $this->heading;?></h1>
		<div class="page-content"><?php echo $this->content['content_value']?></div>
        
		
        
     </div>
    
    
    <!-- begin : team Members -->
    <div class="span4 member-list-main">
    	
        <h1 class="team-heading">&nbsp;</h1>
        <div class="page-content"><?php echo $this->content1['content_value']?></div>
        <p>&nbsp;</p>
        
		
        <div class="row-fluid">
            <div class="span12 bg-2 contact-form-main" >
                <h2>Contact Us Form </h2>
                <?php echo $this->form?>
            </div>
        </div>
                
                
        
        
        
 
     </div>
    <!-- end : team Members -->

</div>
