<?php
 
 ##-----------------------##
 ## ** THEJAMSTOP **
 ##  Show Massagess
 ##-----------------------##
 global $objSession; ?>

<?php if(isset($objSession->defaultMsg)){?>
<div class="alert msgsection alert-block" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>General Alert!</strong> <?php echo $objSession->defaultMsg?>.
    
</div>
<?php unset($objSession->defaultMsg);?>
<?php }?>


<?php if(isset($objSession->infoMsg)){?>
<div class="alert msgsection alert-info" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Info Alert !</strong> <?php echo $objSession->infoMsg?>.
</div>
<?php unset($objSession->infoMsg);?>
<?php }?>



<?php if(isset($objSession->successMsg)){?>
<div class="alert msgsection alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Success Alert !</strong> <?php echo $objSession->successMsg?>.
</div>
<?php unset($objSession->successMsg);?>
<?php }?>


<?php if(isset($objSession->errorMsg)){?>
<div class="alert msgsection alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Error Alert !</strong> <?php echo $objSession->errorMsg?>.
</div>
<?php unset($objSession->errorMsg);?>
<?php }?>

<script>
    
    	setTimeout(function(){ 
		if($('.msgsection').length>0)
		{
			$('.msgsection').slideUp('slow');
		}
		 }, 3000);
    </script>