<div class="list-group">

	<h3 style="margin:0;">ESTATE</h3>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'about_us')?>">About</a>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'contact_us')?>">Contact Us</a>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'terms')?>">Terms</a>
	
	
	<h3>CUSTOMER</h3>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'services')?>">Service</a>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'shipping')?>">Shipping</a>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'returns')?>">Returns</a>
	
	
	<h3>PHILOSOPHY</h3>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'how_it_works')?>">How It Works</a>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'quality')?>">Quality</a>
	<a class="list-group-item"  href ="<?php echo $this->url(array(),'our_promise')?>">Our Promise</a>			

</div>