<style>
body
{
	  background: #eee !important;
}
.bs-example
{
	max-width:545px;
}
.nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus
{
	  border: 1px solid #b3b3b3 !important;
  border-bottom-color: transparent !important;	
  border-radius:4px !important;
}
.nav-tabs
{
	margin-bottom:0px;
	 border-bottom: 1px solid #b3b3b3;
	border-radius:4px !important;
	border-bottom-left-radius:0px !important;
}
.tab-content
{
	  border: 1px solid #b3b3b3;
	  border-top: 0px !important;	
	  padding-left:24px;
	padding-right:24px;
	border-radius:4px !important;
	border-top-left-radius:0px !important;
}.table-toolbar {
  margin-top: -38px;
}


</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
        <div class="col-sm-10 col-md-offset-1">
        <div class="row">
           <!--<a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>-->
           </div>
        	<h1><?php echo $this->pageHeadingshow ?></h1>
            <hr />
            
            <div class="row">
            	<div class="row">
                <form method="post" action="" class="profile_form">
                	<?php echo $this->form->Instrument_name ?>
                    <div class="row">
                      <a class="btn blue btn-primary  btn btn-default pull-right " href="<?php echo SITE_HTTP_URL ?>/class/instruments">Cancel</a>
                    <?php echo $this->form->bttnsubmit ?>
                   
                     </div>
                </form>
           
                  
                </div>
            </div>
            
          <?php 
		  if(isset($this->instrument_data) && !empty($this->instrument_data))
		  {
		  ?>  
        <div class="bs-example">
        <div class="row">
        <ul class="nav nav-tabs">
      		  <li class="active"><a data-toggle="tab" href="#sectionA">Section A</a></li>
       		 <li><a data-toggle="tab" href="#sectionB">Section B</a></li>
        
        </ul>
        <div class="tab-content">
                <div id="sectionA" class="tab-pane fade in active">
               
               		<div class="row">
                	<div class="portlet-body">
                    
              
                        <form action="<?php echo $this->baseUrl() ?>/class/reomvestudent/Instrument_id/<?php echo $this->instrument_data['Instrument_id'] ?>" method="post" onsubmit="return checkSelects();" >
                        <br />
                        <br />
                        <div class="row"></div>
                        <div class="col-md-12">
                        	<label><b>Students currently assigned to instrument</b>  <span class="instrument_add"><a  data-toggle="modal" data-target="#myModal" ><b>(+ Assign Students)</b></a></span></label>
                        </div>
			
				
              
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
								<th width="5%"><input type="checkbox" class="group-checkable"  data-set="#sample_1 .checkboxes"  name="deletebcchk" id="selecctall" /></th>
								
								<th>Last Name</th>
                                <th>First Name</th>
								<th>Added Date</th>
 								
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
                    
                    <div class="table-toolbar">
 					<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Remove Selected From Instrument </button></div>	
                   
				</div>
			
			</form>
                     
				
						
			
			</div>
                </div>
               
               	</div>
               
                <div id="sectionB" class="tab-pane fade">
               
               				<div class="row">
                	<div class="portlet-body">
                    
              
                        <form action="<?php echo $this->baseUrl() ?>/class/removeteachers/Instrument_id/<?php echo $this->instrument_data['Instrument_id'] ?>" method="post" onsubmit="return checkSelects();" >
			 <br />
                        <br />
                        <div class="row"></div>
                        <div class="col-md-12">
                        	<label><b>Teachers currently assigned to instrument</b>  <span class="instrument_add"><a  data-toggle="modal" data-target="#myModalTeacher" ><b>(+ Assign Teachers)</b></a></span></label>
                        </div>
				
              
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_2">
						<thead>
							<tr>
								<th width="5%"><input type="checkbox" class="group-checkable"  data-set="#sample_2 .checkboxes"  name="deletebcchk" id="selecctall2" /></th>
								
								<th>Last Name</th>
                                <th>First Name</th>
								<th>Added Date</th>
 								
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
                    
                    <div class="table-toolbar">
                    
 					<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Remove Selected from Teachers </button></div>	
                    <!--  <a  class="btn red" href="<?php  echo $this->url(array('controller'=>'subscription','action'=>'addplan','module'=>'admin'),'default',true) ?>"> <i class="fa fa-plus"></i> ADD NEW </a>-->
				</div>
			
			</form>
                     
				
						
			
			</div>
                </div>
               
               
                </div>
        
        </div>
        </div>
        </div>
        
        <?php } ?>
         </div>
		</div>
		
		 
	<!--/span-->
    
    

	
</div>
<br />
<br />
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Assign Students</h4>
      </div>
      <div class="modal-body">
	      	<div class="col-md-12">
            <form method="post" class="studentForm" action="<?php echo $this->baseUrl() ?>/class/addstudents/instrument_id/<?php echo $this->instrument_data['Instrument_id'] ?>">
            <div class="row student_form">
       		<?php echo $this->studentform->instrument_student ?>
            </div>
            <?php echo $this->studentform->bttnsubmit ?>
            
            </form>
           </div> 
            </div>
    
    </div>
  </div>
</div>



<!-- Teacher Modal -->
<div class="modal fade" id="myModalTeacher" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Assign Teachers</h4>
      </div>
      <div class="modal-body">
	      	<div class="col-md-12">
            <form method="post" class="teacherForm" action="<?php echo $this->baseUrl() ?>/class/addteachers/instrument_id/<?php echo $this->instrument_data['Instrument_id'] ?>">
            <div class="row student_form">
       		<?php echo $this->teacherform->instrument_teachers ?>
            </div>
            <?php echo $this->teacherform->bttnsubmit ?>
            
            </form>
           </div> 
            </div>
    
    </div>
  </div>
</div>

<script type="text/javascript">




	$(document).ready(function() {
	  $('[data-toggle=offcanvas]').click(function() {
		$('.row-offcanvas').toggleClass('active');
	  });
	});
	
	
	</script>
       <?php 
		  if(isset($this->instrument_data) && !empty($this->instrument_data))
		  {
		  ?>
          
          <script>
	$(document)	 .ready(function(e) {
		
		
		$('#sample_2').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"oLanguage": {
        "sEmptyTable":     "No Record Found"
    				},
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/class/getteacher/Instrument_id/<?php echo $this->instrument_data['Instrument_id'] ?>" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );
		
		
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"oLanguage": {
        "sEmptyTable":     "No Record Found"
    				},
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/class/getstudent/Instrument_id/<?php echo $this->instrument_data['Instrument_id'] ?>" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );
	 $('#selecctall').click(function(event) {  //on click 
	 
        if(this.checked) { // check select status
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = true;  //select all checkboxes with class "checkbox1"               
            });
        }else{
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = false; //deselect all checkboxes with class "checkbox1"                       
            });         
        }
    });
	
	
	 $('#selecctall2').click(function(event) {  //on click 
	
        if(this.checked) { // check select status
            $('.checkbox2').each(function() { //loop through each checkbox
                this.checked = true;  //select all checkboxes with class "checkbox1"               
            });
        }else{
            $('.checkbox2').each(function() { //loop through each checkbox
                this.checked = false; //deselect all checkboxes with class "checkbox1"                       
            });         
        }
    });
	
	
});
</script>

<?php } ?>


 