<style>
body
{
	  background: #eee !important;
}
</style>
<br />
<br /> 
 <div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		<div class="clearfix"></div>
		<div class="custom-form-wrapper">
        	<h5 class="text-center">Welcome "<?php echo  $this->user->user_first_name." ".$this->user->user_last_name; ?>"</h5>
			<h4 class="text-center"><b>Message Folder</b></h4>
            <h5 class="text-center"> <img src="<?php echo HTTP_SITEIMG_PATH ?>/message_folder.png" width="60"  /></h5>
            <br />
            
            <br />
            <div class="row">
            
           	<div class="ad_block_page  padding0">
   
   
    <div class="formborder tab-content container9" >
        <div class="form-body">
       	 <div class="row">
	<div class="col-md-12">
       <div class="portlet box ">
		
        <div class="ad_block_page">
            <div>
                <ul  class="nav nav-tabs" role="tablist">
                   <li role="presentation" >
                       <a href="<?=APPLICATION_URL?>/message/compose" > Compose </a>
                   </li>
                   <li role="presentation" class="active">
                       <a href="<?=APPLICATION_URL?>/message"> Inbox </a>
                   </li>
                   <li role="presentation"  >
                       <a href="<?=APPLICATION_URL?>/message/outbox"> Outbox </a>
                   </li>
                </ul>
             </div>
		<div class="tab-content container9" style=" margin-top:-1px; padding:10px;">
         	    <p>&nbsp;</p>
                <!-------------------------------------------------------------------------------------------------------------------------------------------------------------> 
                    <div id="tab1" class="adtyptabs tab-pane active "  role="tabpanel" >
                    
                    <form method="post" action="<?php echo $this->baseUrl()?>/message/removeinboxmsg"  onsubmit="return checkSelects();" >
                	<div class="table-toolbar">
						<div class="btn-group">
                        	<button id="sample_editable_1_new" class="btn red" style="border:none !important;">
                            <i class="fa fa-trash-o"></i>
                            Delete Selected
                            </button>
                        </div>
                    </div>
                     <br />
                    <table id="sample_1" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                 
                                <th width="5%"><input type="checkbox" class="group-checkable"  data-set="#sample_1 .checkboxes"  name="deletebcchk" id="deletebcchk" /></th>
                                <th>Subject</th>
                                <th>From</th>
                                <th>Messages</th>
                                <th>Started</th>
                                <th>Last Updated</th>
                            
                                 
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    
                    </form>
                
               		 </div>
                <!-------------------------------------------------------------------------------------------------------------------------------------------------------------> 
                 
                 
        </div>
        </div>
	</div>
 
  </div>
</div>
        </div>
    </div>
</div>
                   
                    
             <br />
             <br />
                    
             
            </div>
		</div>
	<!--/span-->
</div>
<br />
<br />
</div>
 


<script type="text/javascript" charset="utf-8">
 
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": false,
		"bServerSide": true,
		"aaSorting": [[ 0,false ]],
	 	"sAjaxSource": "<?php echo $this->baseUrl()?>/message/getmessages",
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2] },
			{ "bSearchable": false, "aTargets": [ 0 ] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {re_init();
		$('.unread').parent().parent().addClass('rowunread');
			}
	} );

	 


});
$("#deletebcchk").change(function () {
    $("input:checkbox").prop('checked', $(this).prop("checked"));
});


</script>