<style type="text/css"> .btn { border:none !important; box-shadow:none !important; padding: 8px 6px; }
.form-horizontal .control-label {
    text-align: right;
}
ul.tagit input[type="text"] { font-size:13px; }
.btn span {
    color: #000;
}
body
{
	  background: #eee !important;
}
</style>
<br />
<br /> 
 <div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		<div class="clearfix"></div>
		<div class="custom-form-wrapper">
        	<h5 class="text-center">Welcome "<?php echo  $this->user->user_first_name." ".$this->user->user_last_name; ?>"</h5>
			<h4 class="text-center"><b>Add Template By Admin</b></h4>
            <h5 class="text-center"> <img src="<?php echo HTTP_SITEIMG_PATH ?>/teacher1.png"  /></h5>
            <br />
            
            <br />
            <div class="row">
            
           	<div class="ad_block_page  padding0">
  
    <div class="formborder tab-content container9" >
        <div class="form-body">
       	 <div class="row">
	<div class="col-md-12">
       <div class="portlet box ">
		
        <div class="row">
	<div class="col-md-12">
      <div class="portlet box blue">
      	
        <div class="portlet-body ad_block_page">
        	<div>
                <ul  class="nav nav-tabs" role="tablist">
                   <li role="presentation" >
                       <a href="<?=APPLICATION_URL?>/message/compose"  > Compose </a>
                   </li>
                   <li role="presentation" <? if($this->getlist=='') { ?> class="active" <? } ?>>
                       <a href="<?=APPLICATION_URL?>/message"> Inbox </a>
                   </li>
                   <li role="presentation" <? if($this->getlist!='') { ?> class="active" <? } ?> >
                       <a href="<?=APPLICATION_URL?>/message/outbox"> Outbox </a>
                   </li>
                </ul>
             </div>
          <div class="tab-content container9" style=" overflow:hidden; padding:10px;">
         	    <p>&nbsp;</p>
                <!-------------------------------------------------------------------------------------------------------------------------------------------------------------> 
                    <div id="tab2" class="adtyptabs tab-pane active "  role="tabpanel" >
                         <div class="col-lg-12">
                                <?php
								if(isset($this->getlist))
								{
									?>
                                    	<div>
                                        <div class="read_msg_margin" style="margin-top:15px;">
                                            <div class="msg_date">
                                            
                                            <?  
											global $timezone;
											
											echo date("d-F-Y",strtotime(datechange($this->messageDetail['message_date'],$timezone))); ?>(<span class="" style="font-weight:normal; font-family: 'gothambook';"><? echo  date("H:i:s A",strtotime($this->messageDetail['message_date'])); ?></span>)
                                                
                                              
                                            </div>
                                        </div>
                                        <div class="read_msg_margin"><? echo ucfirst($this->messageDetail['message_subject']); ?> </div>
                                        
                                        <div class="read_msg_margin"><strong>To:</strong> 
                                            <?   if(empty($this->getlist)) { ?>
                                            <? echo ucfirst( $this->user->user_first_name.'&nbsp;'.$this->user->user_last_name);?> 
                                            <? } else {?>
                                            <? echo $this->messageDetail['message_reciver_id']; ?>
                                            <? } ?>
                                        </div>
                                        
                                        <div class="read_msg_margin"><strong>From:</strong> 
                                            
                                            <? if(!empty($this->getlist)) { ?>
                                            <? echo ucfirst( $this->user->user_first_name.'&nbsp;'.$this->user->user_last_name);?> 
                                            <? } else {?>
                                            <? echo ucfirst($this->messageDetail['user_first_name'].'&nbsp;'.$this->messageDetail['user_last_name']); ?>
                                            <? } ?>
                                            
                                            
                                        </div>
                                       
                                       
                                        <div class="read_msg_margin"><strong>Message:</strong></div>
                                   
                                        
                                        <p class="read_msg_content"><? echo $this->messageDetail['message_content'] ?></p>
                                       
                                         
                                         <!------------------------------------------------------------------------------------------------------------------------------------>
                                         
                                        <p></p>
                                        <? if($this->inbox==1){ ?>
                                        <div><a href="<?=$this->baseUrl()?>/message/compose/remsg/<?=$this->messageDetail['message_sender_id']?>" class="button reply_btn" style=""><i class="glyphicon glyphicon-repeat"></i>Reply</a></div>
                                        <? }?>
                                        <div class="spacer-40"></div>
                                  </div>
                                    <?php	
								}
								else
								{
									?>
                                    	<div class="row">
                                        <ul class="chats ">
                						
                                
                                        	<?php 
												foreach($this->messageDetail as $k=>$v)
												{
													$class="out";
													if($v['user_id']==$this->user->user_id)
													{
														$class="in";	
													}
													?>
                                                    <li class="<?php echo $class ?>">
                                                    <?php 
														if($v['user_image']!='' && file_exists(PROFILE_IMAGES_PATH.'/60/'.$v['user_image']))
														{
															?>
                                                            <img class="avatar" alt="" src="<?php echo HTTP_PROFILE_IMAGES_PATH ?>/60/<?php echo $v['user_image'] ?>">
                                                            <?php
														}
														else
														{
															?>
                                                            <img class="avatar" alt="" src="<?php echo HTTP_PROFILE_IMAGES_PATH ?>/60/default.png">
                                                            <?php	
														 }
													?>
                                                    	
                            											
												<div class="message">
													<span class="arrow"></span>
													<a href="#" class="name"><?php echo $v['user_first_name'].' '.$v['user_last_name'] ?></a>
													<span class="datetime">at  <?php 
													
													global $timezone;
													echo date("M d Y H: A",strtotime(datechange($v['message_date'],$timezone))) ;?></span>
													<span class="body">
                                                    <?php echo $v['message_content'] ?>
													</span>
												</div>
											</li>
                                                    <?php	
												}
											?>
                                               </ul>
                                        </div>
                                        <br />
                                        <div class="row">
                                        	     <div><a href="<?=$this->baseUrl()?>/message/compose/remsg/<?=$this->messageDetail[0]['message_parent_id']?>" class="button reply_btn" style=""><i class="glyphicon glyphicon-repeat"></i>Reply</a></div>
                                        </div>
                                    <?php	
								}
								 ?>
                                    
                            
                        </div>
                    </div>
          </div>
        </div>
       </div>
	</div>
</div>
	</div>
 
  </div>
</div>
        </div>
    </div>
</div>
                   
                    
             <br />
             <br />
                    
             
            </div>
		</div>
	<!--/span-->
</div>
<br />
<br />
</div>
 


