<?php if($this->current_controller=="index" and $this->current_action=="index"){?>
<div class="home-top-footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-7 col-md-7 col-sm-8 text-center">
				<h3>HEADING</h3>
				
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut est odio. Nulla semper blandit sodales. Etiam gravida in dolor in sodales. Cras consectetur.</p>
				
				<p>Nulla scelerisque mollis tortor, et congue urna faucibus a. Duis nulla velit. Nulla facilisi. Ut eget facilisis justo, et accumsan quam. Vivamus in iaculis ligula.</p>
				
				<p>Morbi iaculis augue ac lorem iaculis imperdiet. Morbi consectetur turpis aliquet, posuere lacus eu.</p>
			</div>		
		</div>
	</div>
</div>
<?php  } ?>