<div class="footer-social_block">
	<div class="container">
		<div class="row">
 			<div class="col-lg-6 col-md-6 col-sm-6 footer-signup-wrapper ">
 				<div class="table margin-0">
					<div class="table-row">
						<div class="table-cell cell-input"><input type="text" class=" custom-input"  placeholder="Your Email" name="user_email"  /></div>
						<div class="table-cell cell-submit"><button class="btn-custom btn-gray btn-signup">SIGN UP</button></div>
					</div>
				</div>
			</div>
 			<div class="col-lg-6 col-md-6 col-sm-6 icon-wrapper  ">
				<ul class="social-icons-list">
					<li><a href="<?php echo $this->site_configs['social_link_facebook']?>"><img src="<?php echo HTTP_IMG_PATH?>/icon-facebook.png" alt="facebook" /></a></li>
					<li><a href="<?php echo $this->site_configs['social_link_twitter']?>"><img src="<?php echo HTTP_IMG_PATH?>/icon-twitter.png" alt="twitter" /></a></li>
					<li><a href="<?php echo $this->site_configs['social_link_instagram']?>"><img src="<?php echo HTTP_IMG_PATH?>/icon-instagram.png" alt="instagram" /></a></li>
					<li><a href="<?php echo $this->site_configs['social_link_pinterest']?>"><img src="<?php echo HTTP_IMG_PATH?>/icon-pinterest.png" alt="pinterest" /></a></li>
					<li><a href="<?php echo $this->url(array(),'contact_us')?>"><img src="<?php echo HTTP_IMG_PATH?>/icon-mail.png" alt="mail" /></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
