<style>

body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
        <div class="row">
        <!--   <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>-->
           </div>
        	<h1><?php echo $this->pageHeadingshow ?>  <span class="instrument_add"><a href="<?php   echo $this->url(array('controller'=>'family','action'=>'newfamily'),'default',true) ?>"><b>(+ Family)</b></a></span></h1>
            <hr />
            <div class="row">
            <div class="row">
            	<input type="radio" name="all_family"  value="0" <?php if($this->type==0) { ?> checked="checked" <?php } ?> id="all_family_0" class="all_family"  /> <label for="all_student_0"> <b>View All</b> </label>
                <input type="radio" name="all_family" value="1" <?php if($this->type==1) { ?> checked="checked" <?php } ?>  id="all_family_1" class="all_family" /><label for="all_student_1"> <b> View Active </b> </label>
            </div>
             <br />
            <div class="row">
            	<b class="text-left">If you click on the "Last Name" of a family you will be able to see family Login details. You will also be able to send a 'Password Reset' email, or to resend a "Verification" email </b>
            </div>
                            <div class="row">
                	<div class="portlet-body">
				
						<form action="" name="familyForm" id="familyForm" method="post"  >
			
				<div class="table-toolbar">
 				<!--	<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Delete Selected </button></div>	-->
                    <!--  <a  class="btn red" href="<?php  echo $this->url(array('controller'=>'subscription','action'=>'addplan','module'=>'admin'),'default',true) ?>"> <i class="fa fa-plus"></i> ADD NEW </a>-->
				</div>
              
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
								<th>Last Name</th>
                               	<th>First Name</th>
                                <th>User Status</th>
                                <th width="5%" style="max-width:131px !important" > Username</th>
                                <th width="5%">Email Address</th>
                                <th>Added Date</th>
                               	<th class="desktop">Edit</th>
                                <th><input type="checkbox" name="checkall" id="checkall" /> Select All User</th>
                                <th class="none">Send Verification Mail</th>
                                <th class="none">Verification</th>
                              <!--  <th class="none">Password</th>-->
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			
			</form>
			
			</div>
            <br />
            <div class="row">
            	
                <button class="btn blue btn-primary  btn btn-default pull-right" onclick="removestudent()">Delete User</button>
                <button class="btn blue btn-primary  btn btn-default pull-right marginright_send" onclick="sendmail()">Send Verification Mail</button> &nbsp;
            </div>
                </div>
            </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
		"bAutoWidth": false,
		 "createdRow": function ( row, data, index ) {
		
		   data[8] = data[8].replace(/Passwordtest/g,'Password');
			 },
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/family/getfamily/type/<?php echo $this->type ?>" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2,3,4,5,6,7] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );
	
	
	$('#checkall').click(function(e) {
    var check_val=$(this).val();
	  if($(this).prop("checked") == true)
	  {
               $("input[name='select_users[]']").prop('checked', $(this).prop("checked"));
			    
			   
      }
      else if($(this).prop("checked") == false)
	  {
		   $("input[name='select_users[]']").removeAttr('checked');
           
      }
	
});
});

function removestudent()
{
	if($('input[name="select_users[]"]:checked').length >0)
	{
		var test=confirm("Are you sure you want to remove users?");
		if(test)
		{
			$('#familyForm').attr('action', '<?php echo SITE_HTTP_URL ?>/family/removestudent');
			$('#familyForm').submit();
		}

	}
	else
	{
		alert("Please select users");	
	}
	
		
}

function sendmail()
{
	if($('input[name="select_users[]"]:checked').length >0)
	{
		$('#familyForm').attr('action', '<?php echo SITE_HTTP_URL ?>/family/sendmail');
		$('#familyForm').submit();

	}	
	else
	{
		alert("Please select users");		
	}
}


function removeclass(idval)
{
		var confirmval=confirm("Are you sure you want to remove this family");
		if(confirmval)
		{
			window.location.href="<?php echo SITE_HTTP_URL ?>/family/removefamily/idval/"+idval;
		}
}

$('.all_family').click(function(e) {
  
  var all_val=$(this).val();
  if(all_val==0)
  {
	window.location.href="<?php echo SITE_HTTP_URL ?>/family/index/type/0";	  
  }
  else
  {
	window.location.href="<?php echo SITE_HTTP_URL ?>/family/index/type/1";	  
  }
  
});
</script>


 