<?php 
global $_site_assets_front_admin , $_site_assets_path_front_admin; 

	$_site_assets_front_admin = array(
	'css' =>array(
 		'admin'=>array(
 			'guest'=>array(
				"plugins/font-awesome/css/font-awesome.min.css",
				"plugins/simple-line-icons/simple-line-icons.min.css",
				"plugins/bootstrap/css/bootstrap.min.css",
				"plugins/uniform/css/uniform.default.css",
				"plugins/bootstrap-switch/css/bootstrap-switch.min.css"	,
				"admin_css/login-soft.css",
				"admin_css/components.css",
				"admin_css/plugins.css",
				"admin_css/layout.css",
				"admin_css/default.css",
				"admin_css/custom.css",
				"admin_css/style_custom.css"
			),
			
			'user'=>array(
				"plugins/font-awesome/css/font-awesome.min.css",
				"plugins/simple-line-icons/simple-line-icons.min.css",
				"plugins/bootstrap/css/bootstrap.min.css",
				"plugins/uniform/css/uniform.default.css",
				"plugins/bootstrap-switch/css/bootstrap-switch.min.css",
				"plugins/gritter/css/jquery.gritter.css",
				"plugins/bootstrap-daterangepicker/daterangepicker-bs3.css",
				"plugins/fullcalendar/fullcalendar/fullcalendar.css",
				"plugins/jqvmap/jqvmap/jqvmap.css",
				"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
				"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
				"admin_css/components.css",
				"admin_css/plugins.css",	
				"admin_css/tasks.css",
				"admin_css/layout.css",
				"admin_css/default.css",
				"admin_css/custom.css",	
				"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
				"admin_css/style_custom.css",
 				"module"=>array(
					"static"=>array(
						"graphicmedia"=>array(
							"plugins/fancybox/source/jquery.fancybox.css",
							"admin_css/portfolio.css",
							)
					),
					"index"=>array(
						"browse"=>array(
							"plugins/fancybox/source/jquery.fancybox.css",
							"admin_css/portfolio.css",
							)
					),
					"profile"=>array(
						"image"=>array(
								"plugins/bootstrap-fileinput/bootstrap-fileinput.css"
							)
					
					),
					"user"=>array(
						"account"=>array(
								"admin_css/profile.css"
							),
						"password"=>array(
								"admin_css/profile.css"
							),
						"image"=>array(
								"admin_css/profile.css",
								"plugins/bootstrap-fileinput/bootstrap-fileinput.css"
							)
					
					),
				
				)
 			),
		),
		
		'default'=>array(
		
 			'guest'=>array(
				"front_css/bootstrap.css",
				"front_css/style_custom.css",
				"front_css/lessonrewind.css?".time(),
				"plugins/font-awesome/css/font-awesome.min.css",
 			),
			'user'=>array(
				"front_css/bootstrap.css",
				"front_css/lessonrewind.css?".time(),
				"plugins/font-awesome/css/font-awesome.min.css",
					
				"module"=>array(
					"index"=>array(
						"mobileaudio"=>array(
								"plugins/voicerocoder/demo/style.css",
								"plugins/jquery-file-upload/css/jquery.fileupload.css",
								"plugins/jquery-file-upload/css/jquery.fileupload-ui.css",
						),
					),
					"profile"=>array(
						"image"=>array(
								"plugins/bootstrap-fileinput/bootstrap-fileinput.css"
							),
						"cropimage"=>array(
								"plugins/jcrop/css/jquery.Jcrop.min.css",
 								
							),
						"newannouncement"=>array(
								"plugins/jquery-file-upload/css/jquery.fileupload.css",
								"plugins/jquery-file-upload/css/jquery.fileupload-ui.css",
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
									),
						 "viewannouncement"=>array(
						 		"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
							 ),
						 "viewsubadmin"=>array(
						 		"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
							 ),
						"studentdashboard"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"teacherdashboard"=>array("plugins/bootstrap-select-master/dist/css/bootstrap-select.min.css",),
					),
					"message"=>array(
						"compose"=>array(
										"plugins/chosen-bootstrap/chosen/chosen.css",
										
						),
						"index"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"outbox"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"readmessage"=>array(
											"front_css/style.css",	
						)
						
					),
					"bulkimport"=>array(
						"importteacher"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"importstudent"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"importprivatestudent"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"studentinstrument"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"teacherinstrument"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"studentgroupclasses"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
						"teachergroupclasses"=>array(
										"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
						),
					),
					"class"=>array(
						"index"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
							),
						"instruments"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	
							),
						"newinstrument"=>array(
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	
							),
							
						"newclass"=>array(
								"plugins/bootstrap-daterangepicker/daterangepicker-bs3.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"plugins/datetimepicker-master/jquery.datetimepicker.css",	
							),
					
					
					),
					"teacher"=>array(
						"index"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	
								),
						"alllessons"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	
								),
						"alltemplates"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	
								),
						"uploadfiles"=>array(
								"plugins/jquery-file-upload/css/jquery.fileupload.css",
								"plugins/jquery-file-upload/css/jquery.fileupload-ui.css",
									),
						"newlesson"=>array(
						  		"plugins/voicerocoder/demo/style.css",
								"plugins/jquery-file-upload/css/jquery.fileupload.css",
								"plugins/jquery-file-upload/css/jquery.fileupload-ui.css",
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"front_css/components.css",	
						  ),
						  "addtemplate"=>array(
						  		"plugins/voicerocoder/demo/style.css",
								"plugins/jquery-file-upload/css/jquery.fileupload.css",
								"plugins/jquery-file-upload/css/jquery.fileupload-ui.css",
								
						  ),
						  "createlesson"=>array(
						  		"plugins/voicerocoder/demo/style.css",
								"plugins/jquery-file-upload/css/jquery.fileupload.css",
								"plugins/jquery-file-upload/css/jquery.fileupload-ui.css",
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"front_css/components.css",	
						  ),
						   "createaddtemplate"=>array(
						  		"plugins/voicerocoder/demo/style.css",
								"plugins/jquery-file-upload/css/jquery.fileupload.css",
								"plugins/jquery-file-upload/css/jquery.fileupload-ui.css",
						  ),
						  "viewlessons"=>array(
						  		/*"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	*/
								"plugins/uniform/css/uniform.default.css",
										"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
										"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
										"admin_css/plugins.css",
										"front_css/components.css",	
										"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",
								
						  )
					),
					"family"=>array(
						"index"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	
								)
					),
					"student"=>array(
						"index"=>array(
								"plugins/uniform/css/uniform.default.css",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css",
								"plugins/datatables/extensions/Responsive/css/dataTables.responsive.css",
								"admin_css/plugins.css",
								"front_css/components.css",	
								"plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css",	
								)
					),
					
				),
 				"front_css/style_custom.css",
			),
		)
	),
	'js' =>array(
		'admin'=>array(
			'guest'=>array(
				"plugins/jquery-1.11.0.min.js",
				"plugins/jquery-migrate-1.2.1.min.js",
				"plugins/bootstrap/js/bootstrap.min.js",
				"plugins/uniform/jquery.uniform.min.js",
				"plugins/jquery-validation/js/jquery.validate.min.js",
				"plugins/backstretch/jquery.backstretch.min.js",
				"admin_js/metronic.js",
				"admin_js/layout.js",
				"admin_js/login-soft.js",
			),
			'user'=>array(
  				"plugins/jquery-1.11.0.min.js",
				"plugins/jquery-migrate-1.2.1.min.js",
				"plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js",
				"plugins/jquery-validation/js/jquery.validate.min.js",
				"plugins/jquery-validation/js/additional-methods.min.js",
				"plugins/bootstrap/js/bootstrap.min.js",
				"plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js",
				"plugins/jquery-slimscroll/jquery.slimscroll.min.js",
				"plugins/jquery.blockui.min.js",
				"plugins/jquery.cokie.min.js",
				"plugins/uniform/jquery.uniform.min.js",
				"plugins/bootstrap-switch/js/bootstrap-switch.min.js",
				"plugins/jqvmap/jqvmap/jquery.vmap.js",
				"plugins/flot/jquery.flot.min.js",
				"plugins/flot/jquery.flot.resize.min.js",
				"plugins/flot/jquery.flot.categories.min.js",
				"plugins/jquery.pulsate.min.js",
				"plugins/bootstrap-daterangepicker/moment.min.js",
				"plugins/bootstrap-daterangepicker/daterangepicker.js",
				"plugins/fullcalendar/fullcalendar/fullcalendar.min.js",
				"plugins/jquery-easypiechart/jquery.easypiechart.min.js",
				"plugins/datatables/media/js/jquery.dataTables.min.js",
				"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",
				"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
				"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
				"plugins/ckeditor/ckeditor.js",
				"plugins/jquery.sparkline.min.js",
				"plugins/gritter/js/jquery.gritter.js",
				"admin_js/metronic.js",
				"admin_js/layout.js",
				"admin_js/quick-sidebar.js",
				"admin_js/index.js",
				"plugins/jquery.lazyload.min.js",
				"admin_js/tasks.js",
				
 				"module"=>array(
					"static"=>array(
						"graphicmedia"=>array(
							"plugins/jquery-mixitup/jquery.mixitup.min.js",
							"plugins/fancybox/source/jquery.fancybox.pack.js",
							"admin_js/portfolio.js",
							
							)
					),
					"index"=>array(
						"browse"=>array(
							"plugins/jquery-mixitup/jquery.mixitup.min.js",
							"plugins/fancybox/source/jquery.fancybox.pack.js",
							"admin_js/portfolio.js",
							
							)
					),
					"profile"=>array(
						"image"=>array(
							"plugins/bootstrap-fileinput/bootstrap-fileinput.js",
							
							)
					),
					
					"user"=>array(
						"image"=>array(
							"plugins/bootstrap-fileinput/bootstrap-fileinput.js",
							
							)
					),
					
				),
				
				"admin_js/general.js?=".time(),
  			),
		),
 		
		'default'=>array(
			'guest'=>array(
				"plugins/jquery.pulsate.min.js",
				"plugins/jquery-mixitup/jquery.mixitup.min.js",
				"front_js/bootstrap.min.js",
				"plugins/jquery-validation/js/jquery.validate.min.js",
				"front_js/holder.js",
				"plugins/jquery.lazyload.min.js",
				"plugins/jquery-validation/js/additional-methods.min.js",
				"module"=>array(
					"profile"=>array(
						"image"=>array(
							"plugins/bootstrap-fileinput/bootstrap-fileinput.js",
							
							),
						 "cropimage"=>array(
								"plugins/jcrop/js/jquery.Jcrop.min.js"
							)
							
					),
					 
				),
				"front_js/general.js?=".time(),
				
				
			),
			'user'=>array(
 				"plugins/jquery.pulsate.min.js",
				"front_js/bootstrap.min.js",
				"plugins/jquery.lazyload.min.js",
				"plugins/jquery-validation/js/jquery.validate.min.js",
				"front_js/holder.js",
				"plugins/ckeditor/ckeditor.js",
				"plugins/jquery-validation/js/additional-methods.min.js",
			
				"module"=>array(
					"index"=>array(
						"mobileaudio"=>array(
								"plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js",
									"plugins/jquery-file-upload/js/tmpl.min.js",
									"plugins/jquery-file-upload/js/load-image.min.js",
									"plugins/jquery-file-upload/js/canvas-to-blob.min.js",
									"plugins/jquery-file-upload/js/jquery.blueimp-gallery.min.js",
									"plugins/jquery-file-upload/js/jquery.iframe-transport.js",
									"plugins/jquery-file-upload/js/jquery.fileupload.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-process.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-image.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-audio.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-video.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-validate.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-ui.js",
									"plugins/jquery-file-upload/js/main.js?=".time(),
						),
					),
					"message"=>array(
						"compose"=>array(
							"plugins/chosen-bootstrap/chosen/chosen.jquery.js",
							
						),
						"index"=>array(
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
						),
						"outbox"=>array(
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
						),
					),
					"profile"=>array(
						"image"=>array(
							"plugins/bootstrap-fileinput/bootstrap-fileinput.js",
							
							),
						 "cropimage"=>array(
								"plugins/jcrop/js/jquery.Jcrop.min.js"
							),
						"newannouncement"=>array(
								"plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js",
									"plugins/jquery-file-upload/js/tmpl.min.js",
									"plugins/jquery-file-upload/js/load-image.min.js",
									"plugins/jquery-file-upload/js/canvas-to-blob.min.js",
									"plugins/jquery-file-upload/js/jquery.blueimp-gallery.min.js",
									"plugins/jquery-file-upload/js/jquery.iframe-transport.js",
									"plugins/jquery-file-upload/js/jquery.fileupload.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-process.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-image.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-audio.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-video.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-validate.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-ui.js",
									"plugins/jquery-file-upload/js/main.js?=".time(),
									"plugins/jquery.blockui.min.js",	
								   "plugins/uniform/jquery.uniform.min.js",
								   "plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								   "plugins/datatables/media/js/jquery.dataTables.min.js",
								    "plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
							    	"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								    "plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
					  	  ),
						 "viewannouncement"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
						 	
						 ),
						 "viewsubadmin"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
						 	
						 ),
						  "studentdashboard"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
						 	
						 ),
						 "teacherdashboard"=>array("plugins/bootstrap-select-master/dist/js/bootstrap-select.min.js"),
					),
					"class"=>array(
						"index"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
							),
							
						"newclass"=>array(
								"plugins/bootstrap-daterangepicker/moment.min.js",
								"plugins/bootstrap-daterangepicker/daterangepicker.js",
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								"plugins/nicescroll/jquery.nicescroll.js",	
								"plugins/datetimepicker-master/jquery.datetimepicker.js",	
								
							),
						"instruments"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
									"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
									
										
							
							),
						"newinstrument"=>array(
							"plugins/jquery-migrate-1.2.1.min.js",	
							"plugins/jquery.blockui.min.js",	
							"plugins/uniform/jquery.uniform.min.js",
							"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
							"plugins/datatables/media/js/jquery.dataTables.min.js",
							"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",	
							"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",												
							"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								
					 			
							)
						
						
					
					),
					"teacher"=>array(
						"index"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",		
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",											
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								),
						"alllessons"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",		
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",											
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								),
						"alltemplates"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",		
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",											
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								),
						"uploadfiles"=>array(
								"plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js",
									"plugins/jquery-file-upload/js/tmpl.min.js",
									"plugins/jquery-file-upload/js/load-image.min.js",
									"plugins/jquery-file-upload/js/canvas-to-blob.min.js",
									"plugins/jquery-file-upload/js/jquery.blueimp-gallery.min.js",
									"plugins/jquery-file-upload/js/jquery.iframe-transport.js",
									"plugins/jquery-file-upload/js/jquery.fileupload.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-process.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-image.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-audio.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-video.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-validate.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-ui.js",
									"plugins/jquery-file-upload/js/main.js?=".time(),
					  	  ),
						  "newlesson"=>array(
						  
						  			"plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js",
									"plugins/jquery-file-upload/js/tmpl.min.js",
									"plugins/jquery-file-upload/js/load-image.min.js",
									"plugins/jquery-file-upload/js/canvas-to-blob.min.js",
									"plugins/jquery-file-upload/js/jquery.blueimp-gallery.min.js",
									"plugins/jquery-file-upload/js/jquery.iframe-transport.js",
									"plugins/jquery-file-upload/js/jquery.fileupload.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-process.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-image.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-audio.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-video.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-validate.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-ui.js",
									"plugins/jquery-file-upload/js/main.js?=".time(),
									"plugins/jquery-migrate-1.2.1.min.js",	
									"plugins/jquery.blockui.min.js",	
									"plugins/uniform/jquery.uniform.min.js",
									"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
									"plugins/datatables/media/js/jquery.dataTables.min.js",
									"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",		
									"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",											
									"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
									"plugins/nicescroll/jquery.nicescroll.js",	
						  ),
						  "addtemplate"=>array(
						  			"plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js",
									"plugins/jquery-file-upload/js/tmpl.min.js",
									"plugins/jquery-file-upload/js/load-image.min.js",
									"plugins/jquery-file-upload/js/canvas-to-blob.min.js",
									"plugins/jquery-file-upload/js/jquery.blueimp-gallery.min.js",
									"plugins/jquery-file-upload/js/jquery.iframe-transport.js",
									"plugins/jquery-file-upload/js/jquery.fileupload.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-process.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-image.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-audio.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-video.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-validate.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-ui.js",
									"plugins/jquery-file-upload/js/main.js?=".time(),
						  ),
						   "createlesson"=>array(
						  			"plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js",
									"plugins/jquery-file-upload/js/tmpl.min.js",
									"plugins/jquery-file-upload/js/load-image.min.js",
									"plugins/jquery-file-upload/js/canvas-to-blob.min.js",
									"plugins/jquery-file-upload/js/jquery.blueimp-gallery.min.js",
									"plugins/jquery-file-upload/js/jquery.iframe-transport.js",
									"plugins/jquery-file-upload/js/jquery.fileupload.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-process.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-image.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-audio.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-video.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-validate.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-ui.js",
									"plugins/jquery-file-upload/js/main.js?=".time(),
									"plugins/jquery-migrate-1.2.1.min.js",	
									"plugins/jquery.blockui.min.js",	
									"plugins/uniform/jquery.uniform.min.js",
									"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
									"plugins/datatables/media/js/jquery.dataTables.min.js",
									"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",		
									"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",											
									"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
									"plugins/mediaplayer/jwplayer.js",
						  ),
						  "createaddtemplate"=>array(
						  			"plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js",
									"plugins/jquery-file-upload/js/tmpl.min.js",
									"plugins/jquery-file-upload/js/load-image.min.js",
									"plugins/jquery-file-upload/js/canvas-to-blob.min.js",
									"plugins/jquery-file-upload/js/jquery.blueimp-gallery.min.js",
									"plugins/jquery-file-upload/js/jquery.iframe-transport.js",
									"plugins/jquery-file-upload/js/jquery.fileupload.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-process.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-image.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-audio.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-video.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-validate.js",
									"plugins/jquery-file-upload/js/jquery.fileupload-ui.js",
									"plugins/jquery-file-upload/js/main.js?=".time(),
									
						  ),
						  "viewfolder"=>array(
						  			"plugins/mediaplayer/jwplayer.js",
									
						            ),
						"viewlessons"=>array(
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								
						),
						 "viewdetail"=>array(
						  			"plugins/mediaplayer/jwplayer.js",
									
						            ),
								
						"newteacher"=>array(
							"plugins/nicescroll/jquery.nicescroll.js",	
						),
					),
					"family"=>array(
						"index"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								),
						"newfamily"=>array(
								"plugins/nicescroll/jquery.nicescroll.js",	
						 ),
					),
					"student"=>array(
						"index"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",		
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",											
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
								),
						"newstudent"=>array(
								"plugins/nicescroll/jquery.nicescroll.js",	
						),
					),
					"bulkimport"=>array(
						"importteacher"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",	
						),
						"importstudent"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",	
						),
						"importprivatestudent"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",	
						),
						"studentinstrument"=>array(
										"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",	
						),
						"teacherinstrument"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",	
						),
						"studentgroupclasses"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",	
						),
						"teachergroupclasses"=>array(
								"plugins/jquery-migrate-1.2.1.min.js",	
								"plugins/jquery.blockui.min.js",	
								"plugins/uniform/jquery.uniform.min.js",
								"plugins/bootstrap-switch/js/bootstrap-switch.min.js",	
								"plugins/datatables/media/js/jquery.dataTables.min.js",
								"plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js",													
								"plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js",
								"plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js",
						),
						
						
					),
					"product"=>array(
						 "index"=>array(
								"plugins/jquery-mixitup/jquery.mixitup.min.js"
							)
							
					)
				),
				"front_js/general.js?=".time(),
			),
		)
	),
);





$_site_assets_path_front_admin  = array(
	"css"=>array(
		"admin"=>APPLICATION_URL."/public/",
		"default"=>APPLICATION_URL."/public/",
	),
	"js"=>array(
		"admin"=>APPLICATION_URL."/public/",
		"default"=>APPLICATION_URL."/public/",
	),
);


