<style>
body
{
	  background: #eee !important;
}
.radio-toolbar input[type="radio"] {
    display:none; 
}

.radio-toolbar label {
    display:inline-block;
    background-color:#ddd;
    padding:4px 11px;
    font-family:Arial;
	cursor:pointer;
    font-size:16px;
}

.radio-toolbar input[type="radio"]:checked + label { 
    background-color:#bbb;
}
</style>
<?php
$model = new Application_Model_Static();

?>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper">
        	<?php /*?><h5 class="text-center">Welcome "<?php echo  $this->user->user_first_name." ".$this->user->user_last_name; ?>"</h5>
			<h3 class="text-center"><b>Teacher Dashboard</b></h3>
            <h5 class="text-center"> <img src="<?php echo HTTP_SITEIMG_PATH ?>/teacher1.png"  /></h5><?php */?>
              <br />
          
           <?php /*?> <div class="row">
            <?php 
			if($this->user->user_type=='school' || $this->user->user_type=='schoolsubadmin')
			{
				?>
                 <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl()?>/profile/dashboard">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
                <?php	
			}
			else if($this->user->user_type=='teacher')
			{
				?>
                 <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl()?>/profile/teacherdashboard">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
                <?php
			}
			else if($this->user->user_type=='student')
			{
				?>
                 <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl()?>/profile/studentdashboard">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
                <?php	
			}
			else
			{
				?>
                 <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl()?>/profile/familydashboard">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
                <?php
			}
			?>
           
            </div><?php */?>
           
          
            <br />
            <div class="row">
                    <div class="radio-toolbar">
                    
                    <input type="radio" id="radio1" name="radios" value="0" <?php if(isset($this->check_type) && $this->check_type==0) { ?> checked="checked" <?php } ?> >
                    <label for="radio1">Current</label>  <span> <b style="color:#732627;">(<?php echo $this->current_arr['allval'] ?>)</b></span> &nbsp; &nbsp;
                    
                    <input type="radio" id="radio2" name="radios"value="1" <?php if(isset($this->check_type) && $this->check_type==1) { ?> checked="checked" <?php } ?> >
                    <label for="radio2">Saved </label> <span> <b style="color:#732627;">(<?php echo $this->saved_arr['allval'] ?>)</b></span>
                    
                
                    
                    </div>
            </div>
            <br />
            <div class="row">
            		<div class="allstudents row"><i class="fa fa-bell"></i> All Announcements</div>
                     
                     
                    <div class="viewall row">
                    <br />
                    
                    	<div class="row">
                        <form method="post" id="announceaction" action="<?php echo SITE_HTTP_URL ?>/profile/announceaction">
                        <div class="row">
                        	<button type="button" onclick="check_selected(0)" name="delete_selected" class="btn subscribed_plan">Delete Selected</button>
                            <?php 
							if(isset($this->check_type) && $this->check_type==0)
							{
							?>
                            <button type="button" onclick="check_selected(1)" name="save_selected" class="btn subscribed_plan">Save Selected</button>
                           <?php } ?>
                            <input type="hidden" id="type_val" name="type_val" value="0"  />
                        </div>
                        <br />
                       
                        	<?php
							if(count($this->paginator)>0)
							{
								
								foreach($this->paginator as $k=>$v)
								{
									$ann_arr=$model->Super_Get("announce_attach",'an_un_id="'.$v['announcement_id'].'"','fetchAll');
									?>
                                   <div class="col-md-12 ">
                                   <div class="row lesson">
                                   	<div class="row lesson_div">
                                    <span>
                                    <input type="checkbox" name="chek_selcted[]" value="<?php echo $v['an_id'] ?>"  />	<?php echo $v['announcement_title'] ?>
                                     </span>
                                     <span class="tag bck theme"><?php
									 
									 global $timezone;
									echo date("F, Y h:i A",strtotime(datechange($v['announcement_date'],$timezone))) ;
									   ?></span>
                                    
                                    </div>
                                    <div class="row lesson_desc">
                                    	<?php echo $v['announcement_desc'] ?>
                                    </div>
                                     <? if($ann_arr!='' and count($ann_arr)>0) {
										foreach($ann_arr as $key=>$val) { ?>
                                     <div class="row lesson_desc">
									<a href="<?php echo APPLICATION_URL ?>/download.php?download_file=public/resources/announce_attach/<?php echo $val['an_name']  ?>"><i class="fa fa-download"></i></a> 
                                    </div>
									<? } } ?>
                                   </div>
                                   </div>
                                    <?php
								}	
								   echo $this->paginationControl($this->paginator,'Sliding','pagination-control.phtml');  
							}
							else
							{
								?>
                                <div class="row no_file">
                                	No Announcement added
                                </div>
                                <?php
							}
							 ?>
                           </form>
                        </div>
                    </div>
                    
                   
            </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

<script type="text/javascript">
	function removelesson(idval)
	{
		var testconfirm=confirm("Are you sure you want to remove this lesson");
		if(testconfirm)
		{
			window.location.href="<?php echo $this->baseUrl() ?>/teacher/removelesson/lesson_id/"+idval;	
		}
		
	}
	function check_selected(type)
	{
			if ($('#announceaction :checkbox:checked').length > 0)
			{
				$('#type_val').val(type);
				$('#announceaction').submit();
				
				
			}
			else
			{
				
				alert("Please select any Announcement");	
					
			}
	}
	$("input[name='radios']").change(function(e) {
        
		var thisval=$(this).val();
		window.location.href="<?php echo SITE_HTTP_URL ?>/profile/announcements/check_type/"+thisval;
    });
</script>


 