<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper">
        	<h5 class="text-center">Welcome "<?php echo  $this->user->user_school_name; ?>"</h5>
			<h3 class="text-center"><b>Subscription</b></h3>
           <!-- <a class="pull-right subscribed_plan" href="<?php echo $this->url(array(),'front_dashboard')?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>-->
            <br />
            <br />
            <div class="row">
            	<?php echo $this->form; ?>
            </div>
         
            
		</div>
	<!--/span-->
</div>
<br />
<br />
</div>

<script type="text/javascript">
	$(document).ready(function() {
	  $('[data-toggle=offcanvas]').click(function() {
		$('.row-offcanvas').toggleClass('active');
	  });
	});
</script>


 