<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
      <!--  <div class="row">
           <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
           </div>-->
        	<h1><?php echo $this->pageHeadingshow ?> <span class="instrument_add"><a href="<?php   echo $this->url(array('controller'=>'profile','action'=>'newsubadmin'),'default',true) ?>"><b>(+ Subadmin)</b></a></span></h1>
            <hr />
            <div class="row">
            
            
                <div class="row">
                	<div class="portlet-body">
				
               
						<form action="" method="post"  id="subadminForm" name="subadminForm" >
			
				<div class="table-toolbar">
 				<!--	<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Delete Selected </button></div>	-->
                    <!--  <a  class="btn red" href="<?php  echo $this->url(array('controller'=>'subscription','action'=>'addplan','module'=>'admin'),'default',true) ?>"> <i class="fa fa-plus"></i> ADD NEW </a>-->
				</div>
              
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
							
								
								<th>Last Name</th>
								<th>First Name</th>
                                <th>Email Address</th>
                                <th>User Created</th>
								<th>Edit</th>
                                <th><input type="checkbox" name="checkall" id="checkall" /> Select All User</th>
                                   <th class="none">Send Verification Mail</th>
                                <th class="none">Verification</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			
			</form>
            
           
			
			</div>
            <br />
             <div class="row">
            	
                <button class="btn blue btn-primary  btn btn-default pull-right" onclick="removestudent()">Delete User</button>
                <button class="btn blue btn-primary  btn btn-default pull-right marginright_send" onclick="sendmail()">Send Verification Mail</button> &nbsp;
            </div>
                </div>
            </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/profile/getsubadmin" ,
		"aaSorting": [[ 0, "desc" ]],
		"oLanguage": {
        "sEmptyTable":     "No matching records found"
    				},
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2,3,4,5,6] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );
	$('#checkall').click(function(e) {
    var check_val=$(this).val();
	  if($(this).prop("checked") == true)
	  {
               $("input[name='select_users[]']").prop('checked', $(this).prop("checked"));
			    
			   
      }
      else if($(this).prop("checked") == false)
	  {
		   $("input[name='select_users[]']").removeAttr('checked');
           
      }
	
});
	
});



function removestudent()
{
	if($('input[name="select_users[]"]:checked').length >0)
	{
		var test=confirm("Are you sure you want to remove users?");
		if(test)
		{
		$('#subadminForm').attr('action', '<?php echo SITE_HTTP_URL ?>/profile/removesubadmin');
		$('#subadminForm').submit();
		}

	}
	else
	{
		alert("Please select users");	
	}
	
		
}

function sendmail()
{
	if($('input[name="select_users[]"]:checked').length >0)
	{
		$('#subadminForm').attr('action', '<?php echo SITE_HTTP_URL ?>/profile/sendmail');
		$('#subadminForm').submit();

	}	
	else
	{
		alert("Please select users");		
	}
}
</script>


 