<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
     <!--   <div class="row">
           <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
           </div>-->
        	<h1><?php echo $this->pageHeadingshow ?> <span class="instrument_add"><a href="<?php   echo $this->url(array('controller'=>'profile','action'=>'newannouncement'),'default',true) ?>"><b>(+ Announcement)</b></a></span></h1>
            <hr />
            <div class="row">
            
            
                <div class="row">
                	<div class="portlet-body">
				
               
						<form action="<?php echo $this->baseUrl() ?>/admin/user/remove" method="post" onsubmit="return checkSelects();" >
			
				<div class="table-toolbar">
 				<!--	<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Delete Selected </button></div>	-->
                    <!--  <a  class="btn red" href="<?php  echo $this->url(array('controller'=>'subscription','action'=>'addplan','module'=>'admin'),'default',true) ?>"> <i class="fa fa-plus"></i> ADD NEW </a>-->
				</div>
              
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
								<th width="6%">S.NO</th>
								
								<th>Title</th>
								<th>Description</th>
                                <th>Date</th>
								<th>Edit</th>
                                <th>Delete</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			
			</form>
            
           
			
			</div>
                </div>
            </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/profile/getannouncement" ,
		"aaSorting": [[ 0, "desc" ]],
		"order": [[ 3, "desc" ]],
		"oLanguage": {
        "sEmptyTable":     "No matching records found"
    				},
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );
});

function removeclass(idval)
{
	
		var confirmval=confirm("Are you sure you want to remove this announcement?");
		if(confirmval)
		{
			window.location.href="<?php echo SITE_HTTP_URL ?>/profile/removeannouncement/announcement_id/"+idval;
		}
}
</script>


 