
<div class="row row_signup">
<br />
<div class="form-signin">
	<h1 class="form-signin-heading"><i class="fa fa-key IconColor"></i> <?php echo $this->pageHeading;?></h1>
    <hr />
    <br />
	<h4 class="forgot-instrucation text-center">Please enter your email address below. You will receive a link to reset your password.</h4>
     <br />
	<?php echo $this->form;?>
	<p></p>
	<p class="text-center"><a href="<?php echo $this->url(array(),'front_login')?>">Sign In</a> | <a href="<?php echo $this->url(array(),'front_register')?>">Sign Up</a></p>
    <br />
</div>
</div>