

<div class="row row_signup">
<br />
<div class="form-signin">
	<h1 class="form-signin-heading"><i class="fa fa-key IconColor"></i> <?php echo $this->pageHeading;?></h1>
      <hr />
    <br />
	<?php echo $this->form;?> 
    <br />
     <p>&nbsp;</p>
    <p></p>
    <p class="text-center row"><a href="<?php echo $this->url(array(),'front_login')?>">Sign In</a> | <a href="<?php echo $this->url(array(),'front_register')?>">Sign Up</a></p>
   
    <p>&nbsp;</p>
</div>
</div>