
<style> 
.main-layout-container{ min-height:auto !important;}

.row_signup .form-signin h1{
	    font-size: 21px !important;
}
.row_signup
{
	background-image:url('<?php echo HTTP_SITEIMG_PATH."/slider.jpg" ?>');
	background-position:center;
	background-size:100% 100%;
	background-repeat:no-repeat;
	min-height:auto !important;
  background-attachment: fixed;
  background-repeat: no-repeat;
}
.container{ width:100% !important; max-width:100% !important; padding:0px !important;}
.row_signup label{ font-size:12px !important;}
.form-signin .form-control{ padding:5px !important; }
.row_signup .form-group{ margin-bottom:8px !important;}
.form-signin input[type="submit"], .form-signin button[type="submit"]{     padding: 4px 16px !important;     margin-bottom: 12px !important;}
.register_button {
    margin-top: 0px !important;
}
.row_signup p.text-center a{
	font-size: 11px !important;
	    line-height: 15px !important;
}
.form-signin{ padding:0px 9px !important;}
.form-signin .form-control{ font-size:12px !important;}
hr {
    margin-top: 12px !important;
    margin-bottom: 6px !important; }
</style>
<div class="row row_signup">
<div class="form-signin nomargin" style="margin:0px !important; overflow:hidden;">
	<h1 class="form-signin-heading"><i class="fa fa-user IconColor"></i><?php echo $this->pageHeading;?></h1>
    <hr />
   <form method="post" action="" target="_blank">
   <?php echo $this->form;?>
   </form>
	
	
   
    
</div>
</div>


