<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
        <div class="row">
        <div class="pull-left col-md-6">
        <div class="pull-left">
        <b>Choose Private or Group</b> &nbsp;
          </div>
        	<select name="lesson_class_type" id="lesson_class_type" class="form-control widthauto" >
            	<option value="0" <?php if(isset($this->param) && $this->param=='0') { ?> selected="selected" <?php } ?> >Private</option>
                <option value="1" <?php if(isset($this->param) && $this->param=='1') { ?> selected="selected" <?php } ?>>Class</option>
            </select>
          
        </div>
        
       <!--    <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>-->
           </div>
        	<h1><?php echo $this->pageHeadingshow ?><?php /*?>  <span class="instrument_add"><a href="<?php   echo $this->url(array('controller'=>'teacher','action'=>'newlesson'),'default',true) ?>"><b>(+ Lesson)</b></a></span><?php */?></h1>
            <hr />
            <div class="row">
            
            <div class="row">
				<div class="pull-left col-md-6">
					<div class="pull-left">
						<b>Sort By: </b> &nbsp;
					</div>
					<select name="lesson_sort_by" id="lesson_sort_by" class="form-control widthauto" >
						<option value="0" <?php if(isset($this->status) && $this->status=='0') { ?> selected="selected" <?php } ?> >Date</option>
						<option value="1" <?php if(isset($this->status) && $this->status=='1') { ?> selected="selected" <?php } ?>>Teacher</option>
						<option value="1" <?php if(isset($this->status) && $this->status=='2') { ?> selected="selected" <?php } ?>>
								<?php 
									if($this->param==0)
									{
										echo "Student";	
									}
									else
									{
											echo "Class";
									}
								?>
						</option>
					</select> 
					
					<button class="btn btn-primary">Date</button>
					<button class="btn btn-primary">Teacher</button>
					<button class="btn btn-primary">student</button>
            	</div>

            </div>
                <div class="row">
                	<div class="portlet-body">
				
               
						<form action="<?php echo $this->baseUrl() ?>/admin/user/remove" method="post" onsubmit="return checkSelects();" >
			
				<div class="table-toolbar">
 				<!--	<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Delete Selected </button></div>	-->
                    <!--  <a  class="btn red" href="<?php  echo $this->url(array('controller'=>'subscription','action'=>'addplan','module'=>'admin'),'default',true) ?>"> <i class="fa fa-plus"></i> ADD NEW </a>-->
				</div>
              
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
							<!--	<th width="6%">S.NO</th>-->
								
								<th>Date</th>
								<th>Teacher</th>
								<th>
                                <?php 
								if($this->param==1)
								{
									echo "Class";		
								}
								else
								{
									echo "  Student Name";
								}
								?>
                              
                                </th>
                                <th>Lesson Title</th>
                                <th>Sent / Unsent</th>
                               <th>Edit</th>
                               <th>Delete</th>
 								
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			
			</form>
            
           
			
			</div>
                </div>
            </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getalllessons/param/<?php echo $this->param ?>/status/<?php echo $this->status ?>" ,
		"aaSorting": [[ 0, "desc" ]],
		"oLanguage": {
        "sEmptyTable":     "No matching records found"
    				},
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,4] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );
});

function removeadminlesson(idval)
{
		var confirmval=confirm("Are you sure you want to remove this lesson ?");
		if(confirmval)
		{
			window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/removelesson/lesson_id/"+idval;
		}
}
$('#lesson_class_type').change(function(e) {
    var lesson_class_type=$(this).val();
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/"+lesson_class_type+"/status/<?php echo $this->status ?>";
	
});
$('#lesson_sort_by').change(function(e) {
    
	 var lesson_sort_by=$(this).val();
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/"+lesson_sort_by;
});
</script>


 