<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
        <div class="row">
        <div class="pull-left col-md-6">
        <div class="pull-left">
        <b>Choose Private or Group</b> &nbsp;
          </div>
        	<select name="lesson_class_type" id="lesson_class_type" class="form-control widthauto" >
            	<option value="0" <?php if(isset($this->param) && $this->param=='0') { ?> selected="selected" <?php } ?> >Private</option>
                <option value="1" <?php if(isset($this->param) && $this->param=='1') { ?> selected="selected" <?php } ?>>Class</option>
            </select>
          
        </div>
        
       <!--    <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>-->
           </div>
        	<h1><?php echo $this->pageHeadingshow ?><?php /*?>  <span class="instrument_add"><a href="<?php   echo $this->url(array('controller'=>'teacher','action'=>'newlesson'),'default',true) ?>"><b>(+ Lesson)</b></a></span><?php */?></h1>
            <hr />
            <div class="row">
            
            <div class="row">
				<!-- <div class="pull-left col-md-6"> -->
				<div class="col-md-6">
					<div class="pull-left">
						<label style="font-weight: bold; margin-right:1rem;">Sort By: </label> 						
						<!-- <button class="btn btn-primary"  onclick="sortLessonType(0)">Date</button> -->
						<button class="btn btn-primary"  onclick="sortLessonType(1)">Teacher</button>
						<?php 
							if($this->param==0)
							{
								echo "<button class='btn btn-primary'  style='margin-right:0.5rem;' onclick='sortLessonType(2)'>Student</button>";	
							}else{
								echo "<button class='btn btn-primary'  style='margin-right:0.5rem;' onclick='sortLessonType(2)'>Class</button>";
							}
						?>
					</div>
					<!-- <select name="lesson_sort_by" id="lesson_sort_by" class="form-control widthauto" >
						<option value="0" <?php if(isset($this->status) && $this->status=='0') { ?> selected="selected" <?php } ?> >Date</option>
						<option value="1" <?php if(isset($this->status) && $this->status=='1') { ?> selected="selected" <?php } ?>>Teacher</option>
						<option value="1" <?php if(isset($this->status) && $this->status=='2') { ?> selected="selected" <?php } ?>>
								<?php 
									if($this->param==0)
									{
										//echo "Student";	
									}else{
										//	echo "Class";
									}
								?>
						</option>
					</select>  -->

            	</div>
				<div class="col-md-6">
					<div class="pull-right">
						<div class="form-group">
							<div class="col-md-3">
								<label class="control-label col-md-3" style="padding-top: 1rem; float:right;">Date</label>
							</div>
							<div class="col-md-4" style="margin-right:0.5rem;">
								<div class="input-group input-large date-picker input-daterange" id="date_range" data-date="10/11/2012" data-date-format="mm/dd/yyyy">
									<input type="text" class="form-control" name="from" id="from" value="<?php echo $this->startDate;?>" onchange="sortLessonDate()">
									<span class="input-group-addon">to </span>
									<input type="text" class="form-control" name="to" id="to" value="<?php echo $this->endDate;?>" onchange="sortLessonDate()">
								</div>								
							</div>
						</div>
					</div>
				</div>
            </div>
                <div class="row">
                	<div class="portlet-body">
						<form action="<?php echo $this->baseUrl() ?>/admin/user/remove" method="post" onsubmit="return checkSelects();" >
			
				<div class="table-toolbar">
 				<!--	<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Delete Selected </button></div>	-->
                    <!--  <a  class="btn red" href="<?php  echo $this->url(array('controller'=>'subscription','action'=>'addplan','module'=>'admin'),'default',true) ?>"> <i class="fa fa-plus"></i> ADD NEW </a>-->
				</div>
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
							<!--	<th width="6%">S.NO</th>-->								
								<th>Date</th>
								<th>Teacher</th>
								<th>
									<?php 
									if($this->param==1)
									{
										echo "Class";		
									}else{
										echo "  Student Name";
									}
									?>                              
                                </th>
                                <th>Lesson Title</th>
                                <th>Sent / Unsent</th>
                               <th>Edit</th>
                               <th>Delete</th> 								
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			</form>
			</div>
                </div>
            </div>
		</div>
	<!--/span-->
</div>
<br />
<br />
</div>


<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	// var startDate 	= $("#from").val();
	// var endDate 	= $("#to").val();
	// $("#from").val("<?php echo $this->startDate; ?>");
	// $("#to").val("<?php echo $this->endDate; ?>");

	var startDate = "<?php echo $this->startDate; ?>";
	var startDateArr = startDate.split('/');
	startDate = startDateArr[2] + '-' + startDateArr[0] + '-' + startDateArr[1];
	
	// var endDateArr = $("#to").val().split('/');
	var endDate = "<?php echo $this->endDate; ?>";
	var endDateArr = endDate.trim().split('/');
	endDate = endDateArr[2] + '-' + endDateArr[0] + '-' + endDateArr[1];

	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
 		// "sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getalllessons/param/<?php echo $this->param ?>/status/<?php echo $this->status ?>" ,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getalllessons/param/<?php echo $this->param ?>/status/<?php echo $this->status ?>" + "/startDate/" + startDate + "/endDate/" + endDate,
 		"aaSorting": [[ 0, "desc" ]],
		"oLanguage": {
        "sEmptyTable":     "No matching records found"
    				},
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,4] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );


	handleDatePickers();

});

function removeadminlesson(idval)
{
		var confirmval=confirm("Are you sure you want to remove this lesson ?");
		if(confirmval)
		{
			window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/removelesson/lesson_id/"+idval;
		}
}
$('#lesson_class_type').change(function(e) {
    var lesson_class_type=$(this).val();
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/"+lesson_class_type+"/status/<?php echo $this->status ?>";
	
});
$('#lesson_sort_by').change(function(e) {
    
	 var lesson_sort_by=$(this).val();
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/"+lesson_sort_by;
});

function sortLessonType(lesson_sort_by){	// 0, 1, 2
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/"+lesson_sort_by;
}

function sortLessonDate(){	
	var lesson_sort_by = 0; // Sort by date
	var startDate = $("#from").val().trim();
	var startDateArr = startDate.split('/');
	startDate = startDateArr[2] + '-' + startDateArr[0] + '-' + startDateArr[1];
	
	var endDate = $("#to").val().trim();
	var endDateArr = endDate.split('/');
	endDate = endDateArr[2] + '-' + endDateArr[0] + '-' + endDateArr[1];
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/"+lesson_sort_by + "/startDate/" + startDate + "/endDate/" + endDate;
}

var handleDatePickers = function () {

	if (jQuery().datepicker) {
		$('#date_range').datepicker({
			rtl: Metronic.isRTL(),
			orientation: "left",
			autoclose: true,
			"startDate": "01/01/2015",
			"endDate": "<?php echo date('m/d/Y');?>"
		});	
	}
}
</script>


 