<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
        <div class="row">
			<h1><?php echo $this->pageHeadingshow ?><?php /*?>  <span class="instrument_add"><a href="<?php   echo $this->url(array('controller'=>'teacher','action'=>'newlesson'),'default',true) ?>"><b>(+ Lesson)</b></a></span><?php */?></h1>
            <hr />
            <div class="row">
            	<div class="col-md-4">
					<label class="col-md-7" style="font-weight: bold;padding-top: 1rem;padding-left:0;">Choose Private or Group </label> 	
					<div class="col-md-4">
						<select name="lesson_class_type" id="lesson_class_type" class="form-control widthauto" >
							<option value="0" <?php if(isset($this->param) && $this->param=='0') { ?> selected="selected" <?php } ?> >Private</option>
							<option value="1" <?php if(isset($this->param) && $this->param=='1') { ?> selected="selected" <?php } ?>>Class</option>
						</select>	
					</div>		
				</div>   
				<div class="col-md-4">
					<div class="pull-left" style="padding-top: 0.5rem;">
						<label style="font-weight: bold; margin-right:1rem;">Sort By: </label> 						
						<!-- <button class="btn btn-primary"  onclick="sortLessonType(0)">Date</button> -->
						<button class="btn btn-primary"  onclick="sortLessonType(1)">Teacher</button>
						<?php 
							if($this->param==0)
							{
								echo "<button class='btn btn-primary'  style='margin-right:0.5rem;' onclick='sortLessonType(2)'>Student</button>";	
							}else{
								echo "<button class='btn btn-primary'  style='margin-right:0.5rem;' onclick='sortLessonType(2)'>Class</button>";
							}
						?>
					</div>
					<!-- <select name="lesson_sort_by" id="lesson_sort_by" class="form-control widthauto" >
						<option value="0" <?php if(isset($this->status) && $this->status=='0') { ?> selected="selected" <?php } ?> >Date</option>
						<option value="1" <?php if(isset($this->status) && $this->status=='1') { ?> selected="selected" <?php } ?>>Teacher</option>
						<option value="1" <?php if(isset($this->status) && $this->status=='2') { ?> selected="selected" <?php } ?>>
								<?php 
									if($this->param==0)
									{
										//echo "Student";	
									}else{
										//	echo "Class";
									}
								?>
						</option>
					</select>  -->

            	</div>
				<div class="col-md-4">
					<div class="pull-right">
						<div class="form-group">
							<div class="col-md-2">
								<label class="control-label col-md-3" style="padding-top: 1rem; float:right;">Date</label>
							</div>
							<div class="col-md-8" style="margin-right:0.5rem;">
								<div class="input-group input-medium date-picker input-daterange" id="date_range" data-date="10/11/2012" data-date-format="mm/dd/yyyy">
									<input type="text" class="form-control" name="from" id="from" value="<?php echo $this->startDate;?>" onchange="sortLessonDate()">
									<span class="input-group-addon">to </span>
									<input type="text" class="form-control" name="to" id="to" value="<?php echo $this->endDate;?>" onchange="sortLessonDate()">
								</div>								
							</div>
						</div>
					</div>
				</div>
            </div>
			
			<div class="row" style="margin-top:24px;margin-right:0.5rem;"> 
				<div class="form-horizontal" role="form" id="select_ctrl">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-10 control-label" id="select_label" style="margin-top:4px;">Select</label>
							<div class="col-md-2">
								<select class="form-control" id="select_id">
									<option value="-1"></option>
									<?php 

										if($this->status == 1){
											foreach($this->teacher_data as $k=>$v)
											{								
												if($v['user_id'] == $this->select_id){
													echo '<option value="'.$v['user_id'].'" selected="selected">'.$v['user_first_name'].' '.$v['user_last_name'].'</option>';
												}else{
													echo '<option value="'.$v['user_id'].'">'.$v['user_first_name'].' '.$v['user_last_name'].'</option>';
												}	
											}
										}elseif($this->param == 0 && $this->status == 2){
											foreach($this->student_list as $k=>$v)
											{								
												if($v['user_id'] == $this->select_id){
													echo '<option value="'.$v['user_id'].'" selected="selected">'.$v['user_first_name'].' '.$v['user_last_name'].'</option>';
												}else{
													echo '<option value="'.$v['user_id'].'">'.$v['user_first_name'].' '.$v['user_last_name'].'</option>';
												}	
											}
										}elseif($this->param == 1 && $this->status == 2){
											foreach($this->class_list as $k=>$v)
											{								
												if($v['class_id'] == $this->select_id){
													echo '<option value="'.$v['class_id'].'" selected="selected">'.$v['class_name'].'</option>';
												}else{
													echo '<option value="'.$v['class_id'].'">'.$v['class_name'].'</option>';
												}	
											}
										}
									?>
								</select>
							</div>
						</div>
					</div>
				</div>
			</div> 
			<div class="row">
				<div class="portlet-body">
					<form action="<?php echo $this->baseUrl() ?>/admin/user/remove" method="post" onsubmit="return checkSelects();" >
						<div class="table-toolbar">
						<!--	<div class="btn-group"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Delete Selected </button></div>	-->
							<!--  <a  class="btn red" href="<?php  echo $this->url(array('controller'=>'subscription','action'=>'addplan','module'=>'admin'),'default',true) ?>"> <i class="fa fa-plus"></i> ADD NEW </a>-->
						</div>
						<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
							<thead>
								<tr>
								<!--	<th width="6%">S.NO</th>-->								
									<th>Date</th>
									<th>Teacher</th>
									<th>
										<?php 
										if($this->param==1)
										{
											echo "Class";		
										}else{
											echo "  Student Name";
										}
										?>                              
									</th>
									<th>Lesson Title</th>
									<th>Sent / Unsent</th>
									<th>Missed</th>
									<th>Edit</th>
									<th>Delete</th> 								
								</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!--/span-->
</div>
<br />
<br />
</div>


<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	var status = <?php echo $this->status;?>;
	var param  = <?php echo $this->param;?>;
	if(status == 1){
		$("#select_label").html("Search Teacher");
	}else if(param == 0 && status == 2){
		$("#select_label").html("Search Student");
	}else if(param == 1 && status == 2){
		$("#select_label").html("Search Class");
	}
	var startDate = "<?php echo $this->startDate; ?>";
	var startDateArr = startDate.split('/');
	startDate = startDateArr[2] + '-' + startDateArr[0] + '-' + startDateArr[1];
	
	// var endDateArr = $("#to").val().split('/');
	var endDate = "<?php echo $this->endDate; ?>";
	var endDateArr = endDate.trim().split('/');
	endDate = endDateArr[2] + '-' + endDateArr[0] + '-' + endDateArr[1];

	var select_id = "<?php echo $this->select_id; ?>";
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
		"searching": false,
		// dom: 'lfrtip',
 		// "sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getalllessons/param/<?php echo $this->param ?>/status/<?php echo $this->status ?>" ,
 		// "sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getalllessons/param/<?php echo $this->param ?>/status/<?php echo $this->status ?>" + "/startDate/" + startDate + "/endDate/" + endDate,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getalllessons/param/<?php echo $this->param ?>/status/<?php echo $this->status ?>" + "/startDate/" + startDate + "/endDate/" + endDate + '/select_id/' + select_id,
 		"aaSorting": [[ 0, "desc" ]],
		"oLanguage": {
        			"sEmptyTable":     "No matching records found",
					<?php 
						if($this->status == 1){
							echo '"sSearch": "Search Teacher:"';
						}elseif($this->param == 0 && $this->status == 2){
							echo '"sSearch": "Search Student:"';
						}elseif($this->param == 1 && $this->status == 2){
							echo '"sSearch": "Search Class:"';
						}
					?>
    				},
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,4] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );

	$("#sample_1_length").css("margin-top", "-42px");
	$("#sample_1_wrapper").css("margin-top", "-55px");

	handleDatePickers();
});

function removeadminlesson(idval)
{
		var confirmval=confirm("Are you sure you want to remove this lesson ?");
		if(confirmval)
		{
			window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/removelesson/lesson_id/"+idval;
		}
}
$('#lesson_class_type').change(function(e) {
    var lesson_class_type=$(this).val();
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/"+lesson_class_type+"/status/<?php echo $this->status ?>";
	
});
$('#lesson_sort_by').change(function(e) {
    
	 var lesson_sort_by=$(this).val();
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/"+lesson_sort_by;
});

function sortLessonType(lesson_sort_by){	// 0, 1, 2
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/"+lesson_sort_by;
}

function sortLessonDate(){	
	var lesson_sort_by = 0; // Sort by date
	var startDate = $("#from").val().trim();
	var startDateArr = startDate.split('/');
	startDate = startDateArr[2] + '-' + startDateArr[0] + '-' + startDateArr[1];
	
	var endDate = $("#to").val().trim();
	var endDateArr = endDate.split('/');
	endDate = endDateArr[2] + '-' + endDateArr[0] + '-' + endDateArr[1];
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/"+lesson_sort_by + "/startDate/" + startDate + "/endDate/" + endDate;
}

$('#select_id').change(function(e) {
    var select_id=$(this).val();
	window.location.href="<?php echo SITE_HTTP_URL ?>/teacher/alllessons/param/<?php echo $this->param ?>/status/<?php echo $this->status ?>/select_id/" + select_id;
});

var handleDatePickers = function () {

	if (jQuery().datepicker) {
		$('#date_range').datepicker({
			rtl: Metronic.isRTL(),
			orientation: "left",
			autoclose: true,
			"startDate": "01/01/2015",
			"endDate": "<?php echo date('m/d/Y');?>"
		});	
	}
}
</script>


 