<table cellpadding="0" cellspacing="0" border="0" align="center" width="100%">
<tr>
<td align="center">

<table cellpadding="0" cellspacing="0" border="0" align="center" width="100%">
<tr>
<td align="center" valign="middle">
<?
$data=HTTP_TEMP_PATH.'/'.$this->doc;
//prn($data);
?>
<iframe src="http://docs.google.com/viewer?url=<?=urlencode($data)?>&embedded=true" width="780" height="780" style="border: none;"></iframe>
</td>
</tr>
</table>

</td>
</tr>
</table>