<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		<div class="clearfix"></div>
		<div class="custom-form-wrapper addnew">
        <div class="row">
    <?php /*?>    <?php 
		if($this->user->user_type=='school')
		{
			?>
              <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/dashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
            <?php	
		}
		else
		{
			?>
              <a class="pull-right subscribed_plan" href="<?php echo $this->baseUrl('profile/teacherdashboard') ?>">Go to Dashboard <i class="fa fa-arrow-right"></i></a>
            <?php
		}
		?><?php */?>
                 
           </div>
        	<h1><?php echo $this->pageHeadingshow ?></h1>
            <hr />
            
            <div class="row">
            	<form id="fileupload" action="" method="POST" enctype="multipart/form-data">
            <!-- Redirect browsers with JavaScript disabled to the origin page -->
            <noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="col-md-12 form-group">
            <div id="errormsg" style="display:none;" class="error_div_cls">
    		  </div>   
              
               <div id="errormsgnew" style="display:none; width:500px;" class="error_div_cls">
              
    		  </div>   
           <div class="row">&nbsp;</div>
            <label class="col-md-3 required">
            Upload files	
            </label>
            
                <div class="col-md-9 no_padding" align="left">
                    <!-- The fileinput-button span is used to style the file input field as button -->
                    <span class="btn btn-success fileinput-button">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>Add files...</span>
                        <input type="file" name="files[]" id="uploadify_file" style="font-size:22px;" multiple="multiple"   >
                      
                    </span>
                
                    <!-- The global file processing state -->
                    <span class="fileupload-process"></span>
                </div>
            
                <input type="hidden" name="test"  value="ll"/>
                <!-- The global progress state -->
                <div class="col-lg-5 fileupload-progress fade">
                    <!-- The global progress bar -->
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="height:10px;">
                        <div class="progress-bar progress-bar-success" style="width:0%; display:none;"></div>
                    </div>
                    <!-- The extended global progress state -->
                    <div class="progress-extended" style="height:5px; display:none;">&nbsp;</div>
                </div>
            </div>
            <!-- The table listing the files available for upload/download -->
           
        		<div class="col-md-12 text-center">
                	<img src="" class="presentation_img" id="files_0" style="max-width:1000px; display:none;"/>
                </div>
                
                 <div class="col-md-12 no_padding" style="overflow:hidden;" align="left">
              <table role="presentation" class="table" style="border:solid #141311 1px;"><tbody class="files"></tbody></table>
           		</div>
           <input type="hidden"  value="" name="delete_doc" id="delete_doc" />
          
            
        </form>
        <?php
        if(count($this->document_arr)>0)
		{
		?>
        <table width="100%" border="1" class="table_doc">
        <thead>
        		
        		<th>File Name</th>
                <th>Action</th>
        </thead>
        <?php 
			foreach($this->document_arr as $k=>$v)
			{
				?>
                <tr id="tr_<?php echo $v['teacher_attach_id'];  ?>">
                	<td class="documents">
                    	<?php 
							$ext = pathinfo($v['teacher_attach_name'], PATHINFO_EXTENSION);
							
							if($ext=='mp4')
							{
							?>
                            <img src="<?php echo HTTP_SITEIMG_PATH ?>/video.jpg"  />
                            <?php	
							}
							else if($ext=='doc' || $ext=='DOC' || $ext=='DOCX' || $ext=='docx')
							{
								?>
                               <img src="<?php echo HTTP_SITEIMG_PATH ?>/word-icon.png"  />
                                <?php
							}
							else if($ext=='pdf' || $ext=='PDF')
							{
								?>
                                 <img src="<?php echo HTTP_SITEIMG_PATH ?>/pdf.png"  /> 
                                <?php	
							}
							else 
							{
								?>
                               <img src="<?php echo HTTP_TEACHER_FILES_PATH ?>/<?php echo $v['teacher_attach_name'] ?>"  />  
                                <?php	
							}
						?>
                       &nbsp; &nbsp;
                    	<?php 
						
						if($v['teacher_attach_filename']=='')
										{
										echo $v['teacher_attach_name'];	
										}
										else
										{
											echo $v['teacher_attach_filename'];	
										}
						 ?>	
                    </td>
                   
                    <td class="lesson_icon" >
                    
                    	<a href="<?php echo APPLICATION_URL ?>/download.php?download_file=public/resources/teacher_attachements/<?php echo $v['teacher_attach_name']  ?>"><i class="fa fa-download"></i></a>
                        <a onclick="remove_doc('<?php echo $v['teacher_attach_id'] ?>')"><i class="fa fa-trash-o"></i></a>
                        
                    </td>
                </tr>
                
                <?php	
			}
		?>
        </table>
        <?php } ?>
       
        <br />
        	<button class="pull-right btn blue btn-primary  btn btn-default"  id="savefiles">Save Files</button>
       
        
            </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

 <script>
       var APPLICATION_PATH_USER='<?=SITE_HTTP_URL?>/teacher/uploadpath';
	   
	   $('#savefiles').click(function(e) {
       if($('.template-download').length>0)
	   {
		   $('#fileupload').submit();
		  
		}
		else
		{
			alert("Please Upload Images");	
		}
		
	  
    });
	
	
	function remove_doc(idval)
	{
		var testconfirm=confirm("Are you sure you want to remove this document");
		if(testconfirm)
		{
			$('#tr_'+idval).remove();
			$("#delete_doc").val($("#delete_doc").val()+','+idval);
		}
			
	}
 </script>
 
             
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>


<script id="template-download" type="text/x-tmpl">

{% for (var i=0, file; file=o.files[i]; i++) { 



	if (file.error)
	{
		if(file.error=="Image requires a minimum width")
		{
			alert('Image should be of atleast 200 x 100 pixel.');
		}
		else
		{
	 		alert(file.error);
		}
	}
	else
	{
	
 %}

    <tr class="template-download fade">
        <td>
            <span class="preview" style="cursor:pointer;">
                {% if (file.thumbnailUrl) { %}
                    <img draggable="false"  src="{%=file.thumbnailUrl%}">
                {% } %}
            </span>
        </td>
		<td>
		
		</td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a  title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button  class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
	
	
{% 

		}
		
		
		
} 
	
		
		$('img').on('mousedown', function(e) {
		e.preventDefault();
		});
		
		$('img').bind("contextmenu", function(e) {
		e.preventDefault();
		});
	

%}


</script>

<!-- END EXAMPLE TABLE PORTLET-->



 