<?php

$model = new Application_Model_SuperModel();
$student_id='';
if(isset($this->student_id) && $this->student_id!='')
{
	$student_id=$this->student_id;	
}
else if($this->user->user_type=='student')
{
	$student_id=$this->user->user_id;	
}
?>

<style>
body
{
	  background: #eee !important;
}
.lesson_desc
{
	font-size:16px;
}
</style>



<div class="row row-offcanvas row-offcanvas-left">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper">
        	<?php /*?><h5 class="text-center">Welcome "<?php echo  $this->user->user_first_name." ".$this->user->user_last_name; ?>"</h5>
			<h3 class="text-center"><b>Teacher Dashboard</b></h3>
            <h5 class="text-center"> <img src="<?php echo HTTP_SITEIMG_PATH ?>/teacher1.png"  /></h5><?php */?>
              <br />
          
       
          
            <br />
         
            <br />
            <div class="row addnew">
            <h1 class="static-content-heading"><?php echo $this->pageHeadingshow;?></h1>
                	<div class="portlet-body">
				
						<form action="<?php echo $this->baseUrl() ?>/admin/user/remove" method="post" onsubmit="return checkSelects();" >
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
						
								
								<th>Date</th>
                                <th>Teacher</th>
                                <th>Lesson Title</th>
                                <th>Sent/Unsent</th>
                                <th>View Lesson</th>
                                <!--<th>Lesson Viewed</th>-->
                             
                               
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			
			</form>
			
			</div>
                </div>
		</div>
		
		 
	<!--/span-->

	
</div>
<br />
<br />
</div>

<script type="text/javascript" charset="utf-8">
<?php 
if(isset($this->student_id) && $this->student_id!='')
{
	
?>
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
  		"bAutoWidth": false,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getlessons/student_id/<?php echo $this->student_id ?>" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2,3] },
 		 	
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		$('.labelLeft').text('No');
		$('.labelRight').text('Yes');
	
		
		}
	} );
});
<?php  } 

else if(isset($this->teacher_id) && $this->teacher_id!='' or ($this->user->user_type=='teacher'))
{
	if($this->user->user_type=='teacher')
	{
		$this->teacher_id=$this->user->user_id;		
	}
	
	?>
		$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
  		"bAutoWidth": false,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getlessonsteacher/teacher_id/<?php echo $this->teacher_id ?>" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2,3] },
 		
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		
		
		}
	} );
});
	<?php
}
 ?>
function removeclass(idval)
{
		var confirmval=confirm("Are you sure you want to remove this family");
		if(confirmval)
		{
			window.location.href="<?php echo SITE_HTTP_URL ?>/student/removestudent/idval/"+idval;
		}
}

$('.all_student').click(function(e) {
  
  var all_val=$(this).val();
  if(all_val==0)
  {
	window.location.href="<?php echo SITE_HTTP_URL ?>/student/index/type/0";	  
  }
  else
  {
	window.location.href="<?php echo SITE_HTTP_URL ?>/student/index/type/1";	  
  }
  
});

	function removelesson(idval)
	{
		var testconfirm=confirm("Are you sure you want to remove this lesson");
		if(testconfirm)
		{
			window.location.href="<?php echo $this->baseUrl() ?>/teacher/removelesson/lesson_id/"+idval;	
		}
		
	}

$('.btn_swicth').click(function(){
	var lesson_id=($(this).attr('id')).split("_");
	if($(this).hasClass('locked_active') || $(this).hasClass('unlocked_inactive')){
		/* code to do when unlocking */
        $('#switch_status').html('Switched on.');
		
	}else
	{
		
		/* code to do when locking */
        $('#switch_status').html('Switched off.');
			
	}
	if(lesson_id[0]=='yes')
		{
				changestatus(1,lesson_id[1]);	
		}	
		else
		{
				changestatus(0,lesson_id[1]);	
		}
	/* reverse locking status */
	$('#yes_'+lesson_id[1]).toggleClass('locked_inactive locked_active btn-default btn-info');
	$('#no_'+lesson_id[1]).toggleClass('unlocked_inactive unlocked_active btn-info btn-default');
});

function changestatus(status,lesson_id)
{
	$('#wrap').show();
	$.ajax({ //Process the form using $.ajax()
            type      : 'POST', //Method type
            url       : '<?php echo SITE_HTTP_URL ?>/teacher/changestatus/status/'+status+'/lesson_id/'+lesson_id+'/student_id/<?php echo $student_id ?>', //Your form processing file URL
            data      : "", //Forms name
            success   : function(data)
			 {
				$('#wrap').hide();	
			
			 }
        });
}
$('.viewcount').click(function(e) {
	
    var idval=$(this).attr('id');
	var idval_text=idval.split('_');
	//alert(idval_text[1]);
	if($('#popOverBox_'+idval_text[1]).is(':visible'))
	{
		$('#popOverBox_'+idval_text[1]).slideUp('slow');	
	}
	else
	{
		$('#popOverBox_'+idval_text[1]).slideDown('slow');		
	}
});
</script>
 