<?php
$model = new Application_Model_SuperModel();

?>

<style>
body
{
	  background: #eee !important;
}
</style>
<h1 class="static-content-heading"><?php echo $this->content['page_title'];?></h1>

<div class="row row-offcanvas row-offcanvas-left lessonclass">
	<div class="col-sm-12">
		
		<div class="clearfix"></div>
		<div class="custom-form-wrapper lessonclassinner">
        	
            
           
          
            <br />
            <div class="row">
            		<div class="allstudents row text-center"><span class="pull-left"><i class="fa fa-book"></i> All Lessons</span> 
                    	All sent or unsent lessons for "<?php echo $this->student_arr['user_first_name'].' '.$this->student_arr['user_last_name']; ?>"
						<span class="pull-right"><a style="float: right; color: white;" class="print_btn" onclick="window.print()"><i style="color: white;" class="fa fa-print"></i> Print</a></span>
                    </div>
                     
                    <div class="viewall row">
                    <br />
                    <div class="portlet-body">
				
						<form  method="post"  >
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
								<th>Date</th>
                                <th>Teacher</th>
                                <th>Student Name</th>
                                <th>Lesson Title</th>
                                <th>Sent/Unsent</th>
                                <th>Edit/View</th>
                                <th>Delete</th>
                             
                               
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			
			</form>
			
			</div>
                    	<?php /*?><div class="row">
                        <br />
                       
                        	<?php
							if(count($this->paginator)>0)
							{
								
								foreach($this->paginator as $k=>$v)
								{
									$attachments=$model->Super_Get("lession_attach","la_lesson_id='".$v['lesson_id']."'","fetch",array("fields"=>array("COUNT('la_lesson_id') as lessoncount")));
								
								
									?>
                                   <div class="col-md-12 ">
                                   <div class="row lesson">
                                   	<div class="row lesson_div">
                                    <span>
                                    	<?php echo $v['lesson_title'] ?>
                                     </span>
                                     <span class="tag bck theme"><?php echo date('F, Y h:i A', strtotime($v['lesson_date'])) ?></span>
                                     <span class="pull-right lesson_icon">
                                     <?php
									 if($this->user->user_type=='school' || $this->user->user_type=='teacher' || $this->user->user_type=='schoolsubadmin')
									 {
										 ?>

                                         <?php
										}
										if(isset($this->student_id) && !empty($this->student_id) && isset($this->teacher_id) && !empty($this->teacher_id))
										{
											?>
                                            <a href="<?php  echo $this->url(array('controller'=>'teacher','action'=>'viewdetail','lesson_id'=>$v['lesson_id'],'student_id'=>$this->student_id,'teacher_id'=>$this->teacher_id,'student_id'=>$this->student_id),'default',true) ?>"><i class="fa fa-search"></i></a>
                                            <?php	
										}
										else if(isset($this->student_id) && !empty($this->student_id))
										{
											?>
                                            	<a href="<?php  echo $this->url(array('controller'=>'teacher','action'=>'viewdetail','lesson_id'=>$v['lesson_id'],'student_id'=>$this->student_id),'default',true) ?>"><i class="fa fa-search"></i></a>
                                            <?php	
										}
										else if(isset($this->teacher_id) && !empty($this->teacher_id))
										{
											?>
                                            	<a href="<?php  echo $this->url(array('controller'=>'teacher','action'=>'viewdetail','lesson_id'=>$v['lesson_id'],'teacher_id'=>$this->teacher_id),'default',true) ?>"><i class="fa fa-search"></i></a>
                                            <?php	
										}
										else
										{
											?>
                                            	<a href="<?php  echo $this->url(array('controller'=>'teacher','action'=>'viewdetail','lesson_id'=>$v['lesson_id']),'default',true) ?>"><i class="fa fa-search"></i></a>
                                            <?php
										}
									  ?>
	                                   
                                     
                                      
                                     </span>
                                    
                                    <div class="row lesson_desc">
                                    	<?php echo $v['lesson_desc'] ?>
                                         <?php if(isset($attachments) && !empty($attachments) && !empty($attachments['lessoncount']) && $attachments['lessoncount']>0)
									 { ?>
                                     <a class="pull-right" href="<?php  echo $this->url(array('controller'=>'teacher','action'=>'viewdetail','lesson_id'=>$v['lesson_id']),'default',true) ?>" />
                                     <span class="tag bck theme">View all attachement </span>
                                     
                                     </a>
                                     <?php } ?>
                                    </div>
                                    
                                    <?php
									if($this->user->user_type=='teacher')
									{
										?>
                                        <div class="row">
                                      	<?php 
										$saved='';
										if($v['lesson_status']==0)
										{
											$saved='Saved Without Sending';	
											?>
                                            <span class="tag bck theme"><?php echo $saved; ?></span>
                                            <?php
										}
										else
										{
											$saved='Send to Students';	
											?>
                                            <span class="tag bck theme"><?php echo $saved; ?></span>
                                            <?php
										}
										$template='';
										if($v['lesson_template']==1)
										{
												?>
                                              <span class="tag bck theme">Saved As Template</span>
                                                <?
										}
										?>
                                        
                                        </div>
                                        <?php	
									}
									 ?>
                                    </div>
                                   </div>
                                   </div>
                                    <?php
								}	
								
								   echo $this->paginationControl($this->paginator,'Sliding','pagination-control.phtml');  
							}
							else
							{
								?>
                                <div class="row no_file">
                                	No Lesson added
                                </div>
                                <?php
							}
							 ?>
                        </div><?php */?>
                    </div>
                    
                   
            </div>
		</div>
		
		 


	
</div>
<br />
<br />
</div>

<script type="text/javascript">
	function removelesson(idval)
	{
		var testconfirm=confirm("Are you sure you want to remove this lesson");
		if(testconfirm)
		{
			window.location.href="<?php echo $this->baseUrl() ?>/teacher/removelesson/lesson_id/"+idval;	
		}
		
	}
	$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"responsive": true,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/teacher/getstudentlessons/student_id/<?php echo $this->student_id ?>" ,
		"aaSorting": [[ 0, "desc" ]],
		"oLanguage": {
        "sEmptyTable":     "No matching records found"
    				},
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,4] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
		re_init();
		}
	} );
});
	
</script>


 